// ══════════════════════════════════════════════════════════════
//  突然変異チェック。node tools/mutate.js で走る。
//
//  テストそのものが機能しているかを確かめる道具。本体をわざと壊して、
//  tools/test.js が落ちるかを見る。落ちなければ、その挙動は誰も見張っていない。
//
//  ここに並べてあるのは、実際にこのゲームで起きたバグの再現。
//  本体は毎回かならず元に戻す（途中で止めても復元されるよう finally で囲ってある）。
// ══════════════════════════════════════════════════════════════
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const GAME = path.join(__dirname, '..', 'invader_game.html');
// 二重に走らせない。この道具は本体を書き換えてから戻すので、
//  同時に2つ動くと 片方の書き戻しがもう片方の変異を「元の姿」として
//  固定してしまい、本体に壊れたコードが residue として残る（実際に起きた）。
const LOCK = path.join(__dirname, '.mutate.lock');
try{
  fs.writeFileSync(LOCK, String(process.pid), { flag: 'wx' });
}catch(e){
  console.error('別の突然変異チェックが動いています。終わってから実行してください。');
  console.error('（前回が異常終了した場合は ' + LOCK + ' を消してください）');
  process.exit(1);
}
const unlock = () => { try{ fs.unlinkSync(LOCK); }catch(e){} };
process.on('exit', unlock);
process.on('SIGINT', () => { unlock(); process.exit(130); });
const TEST = path.join(__dirname, 'test.js');

// [名前, 置換前, 置換後, 期待]  期待='caught' … 検出できるべき
//                               期待='equivalent' … 壊しても挙動が変わらない（検出できなくてよい）
const MUTATIONS = [
  ['わがままを満腹より先に見る（しかって直しても結局食べず、原因が読めない）',
   "        else if(pet.hunger >= HUNGER_MAX && pTrait() > -0.5){",
   "        else if(pet.tantrumAt || rollTantrum('feed')){ leavePlate('meal'); setReaction('refuse'); }\n        else if(pet.hunger >= HUNGER_MAX && pTrait() > -0.5){", 'caught'],
  ['満腹でも 嫌がる仕草を出す（わがままの拒否と区別がつかない）',
   "          leavePlate('meal');                                       // 満腹：無反応で皿だけ残す",
   "          leavePlate('meal'); setReaction('refuse');", 'caught'],
  ['満腹の判定から性格を外す（おっとりも満腹で食べなくなる）',
   "pet.hunger >= HUNGER_MAX && pTrait() > -0.5", "pet.hunger >= HUNGER_MAX", 'caught'],
  ['ごはんを ふれあいに数えない（毎日世話をしても なかよしが下がる）',
   "          markTouch('feed');\n", "", 'caught'],
  ['ごはんで なかよしの点が入る（ふれあい無しでも旅立ちに届く）',
   "          markTouch('feed');",
   "          if(pet.hunger <= 1) gainB(1, 'feed');\n          markTouch('feed');", 'caught'],
  ['ふれあい1種類でも減らす（そうじだけの日を罰する）',
   "return touches >= 2 ? 0 : (touches === 1 ? 2 : 5);", "return touches >= 1 ? 2 : 5;", 'caught'],
  ['なかよしの初期値を 目盛の帯の下端に置く（数日 手応えが無い）',
   "C:50, B:40, W:0", "C:50, B:35, W:0", 'caught'],
  ['なかよしの上限を連続日数と無関係にする',
   'const BOND_CAP = [1, 1, 2, 2, 3];', 'const BOND_CAP = [5, 5, 5, 5, 5];', 'caught'],
  ['ふれあいを種類ではなく回数で数える',
   'if(!k[kind]){ k[kind] = 1; pet.touchCount = (pet.touchCount||0) + 1; }',
   'pet.touchCount = (pet.touchCount||0) + 1;', 'caught'],
  ['治した病気も放置に数える',
   'const sickLeft = d.sick && !d.cured;', 'const sickLeft = d.sick;', 'caught'],
  ['ワイルドにもお迎えが来るようにする',
   "      if(isWild()){\n        // とげとげの行き先。", "      if(false){\n        // とげとげの行き先。", 'caught'],
  ['潜伏中でもくすりを嫌がる',
   "else if(pet.incubAt){", "else if(false){", 'caught'],
  ['恨みが溜まっていても帰還を止めない',
   "if(wrathful() && pet.stage !== 'final') return;", '', 'caught'],
  ['ワイルドでなくても侵攻する',
   "if(pet.stage !== 'final' || !isWild()) return false;",
   "if(pet.stage !== 'final') return false;", 'caught'],
  ['夜に始めると、来た直後に寝てしまう',
   "    pet.wokeUntil = Date.now() + ARRIVE_AWAKE_MS;   // 就寝時間帯に来てもしばらくは起きている", "", 'caught'],
  ['起きている時間が極端に短い',
   "  const ARRIVE_AWAKE_MS = 30 * 60000;", "  const ARRIVE_AWAKE_MS = 1000;", 'caught'],
  ['起きている時間が長すぎて、いつまでも寝ない',
   "  const ARRIVE_AWAKE_MS = 30 * 60000;", "  const ARRIVE_AWAKE_MS = 12 * 3600000;", 'caught'],
  ['名前をつけても時間の起点がそろわない',
   "    pet.lastTick = Date.now();\n    pet.wokeUntil = Date.now() + ARRIVE_AWAKE_MS;",
   "    pet.wokeUntil = Date.now() + ARRIVE_AWAKE_MS;", 'caught'],
  ['夜型シフトを無くす',
   'const OWL_MAX = 5;', 'const OWL_MAX = 0;', 'caught'],
  ['満腹にしても時計を数え直さない（メーターが満タンにならない）',
   "    if(pet.hunger >= HUNGER_MAX && before < HUNGER_MAX) pet.hungerAcc = 0;", "", 'caught'],
  ['満腹でなくても時計を数え直す（いつまでも減らない）',
   "    if(pet.hunger >= HUNGER_MAX && before < HUNGER_MAX) pet.hungerAcc = 0;",
   "    pet.hungerAcc = 0;", 'caught'],
  ['満腹のままおやつを与えても時計が巻き戻る（永久に空腹にならない）',
   "    if(pet.hunger >= HUNGER_MAX && before < HUNGER_MAX) pet.hungerAcc = 0;",
   "    if(pet.hunger >= HUNGER_MAX) pet.hungerAcc = 0;", 'caught'],
  ['きげんを上げても時計を数え直さない（満タンにならない）',
   "      if(pet.mood >= MOOD_MAX) pet.moodAcc = 0;", "", 'caught'],
  ['汚れていても、きげんの時計を数え直してしまう',
   "      if(pet.mood >= MOOD_MAX) pet.moodAcc = 0;", "      pet.moodAcc = 0;", 'caught'],
  ['汚れていてもきげんが満タンまで上がる',
   "  function moodCap(){ return (dirtCount() > 0 || pet.health === 'SICK') ? MOOD_MAX - 1 : MOOD_MAX; }",
   "  function moodCap(){ return MOOD_MAX; }", 'caught'],
  ['ごはんの回復量を段階で変えない',
   "const FEED_GAIN  = { egg: 3, mid: 3, larva: 2, adult: 1, final: 1 };",
   "const FEED_GAIN  = { egg: 1, mid: 1, larva: 1, adult: 1, final: 1 };", 'caught'],
  ['なかよしの上限（100）を外す',
   'pet.B = Math.min(100, pet.B + add);', 'pet.B = pet.B + add;', 'caught'],
  ['読めなかったセーブを黙って捨てる（控えも退避もしない）',
   "  let pet = loadPet() || defaultPet();",
   "  let pet = (()=>{ try{ const sv = JSON.parse(localStorage.getItem(SAVE_KEY)); if(sv && sv.name) return migratePet(sv); }catch(e){} return null; })() || defaultPet();", 'caught'],
  ['読み込めても控えを残さない',
   "if(p){ try{ localStorage.setItem(SAVE_BAK, main); }catch(e){} return p; }",
   "if(p){ return p; }", 'caught'],
  ['読めなかった原文を退避せずに捨てる',
   "      try{ if(main) localStorage.setItem(SAVE_BAD, main); }catch(_){}", "", 'caught'],
  ['本体が壊れていても控えを見に行かない',
   "    if(!broken) return null;", "    return null;", 'caught'],
  ['まだ子がいないだけでも控えを掘り起こす',
   "    if(!broken) return null;", "", 'caught'],
  ['控えから戻すときに移行を通さない',
   "  function readSave(raw){\n    if(!raw) return null;\n    const sv = JSON.parse(raw);\n    return (sv && sv.name) ? migratePet(sv) : null;\n  }",
   "  function readSave(raw){\n    if(!raw) return null;\n    const sv = JSON.parse(raw);\n    return (sv && sv.name) ? Object.assign(defaultPet(), sv) : null;\n  }", 'caught'],
  ['ALL RESET で控えと退避が残る（あとで前の子が掘り起こされる）',
   "      try{ [SAVE_KEY, SAVE_BAK, SAVE_BAD].forEach(k => localStorage.removeItem(k)); }catch(e){}",
   "      try{ localStorage.removeItem(SAVE_KEY); }catch(e){}", 'caught'],
  ['セーブ移行をせず、既定値まかせに戻す',
   'return (sv && sv.name) ? migratePet(sv) : null;',
   'return (sv && sv.name) ? Object.assign(defaultPet(), sv) : null;', 'caught'],
  ['古いセーブに口調を与えない',
   "if(!p.voice && (p.stage === 'adult' || p.stage === 'final')) p.voice = pickVoice(p);", '', 'caught'],
  ['古いセーブのワイルドの印を復元しない',
   "        p.formWild = /3$/.test(p.form || '') && !wasHiddenRoute(p);",
   '        p.formWild = false;', 'caught'],
  ['古いセーブで、隠しルートで進化した子もワイルド扱いにする',
   "&& !wasHiddenRoute(p);", ';', 'caught'],
  ['与えすぎがプリックリーを上書きできてしまう（順序の入れ替え）',
   "if(pet.C < C_FORM_BAD || (pet.M||0) >= M_FORM_BAD){ pet.formWild = true; return key + '3'; }\n    if(bigEater() || pampered()) return key + '1';",
   "if(bigEater() || pampered()) return key + '1';\n    if(pet.C < C_FORM_BAD || (pet.M||0) >= M_FORM_BAD){ pet.formWild = true; return key + '3'; }", 'caught'],
  ['与えすぎがプランプではなくスリークになる',
   "if(bigEater() || pampered()) return key + '1';",
   "if(bigEater() || pampered()) return key + '2';", 'caught'],
  ['甘やかしの道をふさぐ',
   "if(bigEater() || pampered()) return key + '1';",
   "if(bigEater()) return key + '1';", 'caught'],
  ['甘やかしが大食いを兼ねてしまう（片方だけで通る）',
   "if(bigEater() || pampered()) return key + '1';",
   "if(bigEater() && pampered()) return key + '1';", 'caught'],
  ['甘やかしの条件がおやつだけで通ってしまう',
   "return (s.highBDays||0) >= PAMPER_DAYS && ((s.total||{}).snack||0) >= PAMPER_SNACKS; }",
   "return ((s.total||{}).snack||0) >= PAMPER_SNACKS; }", 'caught'],
  ['甘やかしの条件がなかよしだけで通ってしまう',
   "return (s.highBDays||0) >= PAMPER_DAYS && ((s.total||{}).snack||0) >= PAMPER_SNACKS; }",
   "return (s.highBDays||0) >= PAMPER_DAYS; }", 'caught'],
  ['なかよしの連続日数が切れなくなる',
   "pet.highBDays = (pet.B >= B_PAMPER) ? (pet.highBDays||0) + 1 : 0;",
   "pet.highBDays = (pet.highBDays||0) + 1;", 'caught'],
  ['なかよしを保つ線を下げる',
   "const B_PAMPER = 80, PAMPER_DAYS = 5, PAMPER_SNACKS = 25;",
   "const B_PAMPER = 0, PAMPER_DAYS = 5, PAMPER_SNACKS = 25;", 'caught'],
  ['条件がそろわなくても最終形態にしてしまう',
   "    return '';                                                          // まだ最終形態にならない",
   "    return key + '2';", 'caught'],
  ['成体で止める判断を無視して進化させる',
   "      if(!f) return;                              // どの条件にも当たらないうちは成体のまま待つ",
   "      if(!f) { pet.form = 'i2'; }", 'caught'],
  ['すらりの併用ルートが、片方だけで通ってしまう',
   "if(pet.C >= C_FORM_GOOD && allRounderSoft()) return key + '2';",
   "if(pet.C >= C_FORM_GOOD || allRounderSoft()) return key + '2';", 'caught'],
  ['ミニゲームの基準を下げる',
   "const ALLROUND = { sw: 600, ss: 700, ab: 400 };",
   "const ALLROUND = { sw: 1, ss: 1, ab: 1 };", 'caught'],
  ['おもいでから あそんだ回数が消える',
   "      PLAY_ITEMS.forEach((label,i)=> memGameRow(label, bestText(i), playText(i), 32 + i*8));",
   "      PLAY_ITEMS.forEach((label,i)=> memBestRow(label, bestText(i), 32 + i*8));", 'caught'],
  ['あそんだ回数が、未プレイでも 0 と出る（ベストと作法が食い違う）',
   "    if(!(Number.isFinite(p[k]) && p[k] > 0)) return '---';\n    return String(Math.max(0, Math.round(p[k])));",
   "    return String(Math.max(0, Math.round(p[k]||0)));", 'caught'],
  ['おもいでの2列が重なる（ベスト列を右へ寄せすぎ）',
   "  const MEM_BEST_R = 39, MEM_PLAY_R = 51;",
   "  const MEM_BEST_R = 48, MEM_PLAY_R = 51;", 'caught'],
  ['あそんだ回数が画面の外へはみ出す',
   "  const MEM_BEST_R = 39, MEM_PLAY_R = 51;",
   "  const MEM_BEST_R = 39, MEM_PLAY_R = 56;", 'caught'],
  ['なつかれないままの子が、どの結末にも辿り着けなくなる',
   "    const bad = sg.includes('notouch') || sg.includes('lowB') || sg.length >= 2;",
   "    const bad = sg.includes('notouch') || sg.length >= 2;", 'caught'],
  ['兆候1つで家出になってしまう（遊ばないだけで出ていく）',
   "    const bad = sg.includes('notouch') || sg.includes('lowB') || sg.length >= 2;",
   "    const bad = sg.length >= 1;", 'caught'],
  ['ふれあいゼロが単独で成立しなくなる',
   "    const bad = sg.includes('notouch') || sg.includes('lowB') || sg.length >= 2;",
   "    const bad = sg.includes('lowB') || sg.length >= 2;", 'caught'],
  ['恨みが最終形態に効かなくなる（構い倒しても素直に育つ）',
   "    if(pet.C < C_FORM_BAD || (pet.M||0) >= M_FORM_BAD){ pet.formWild = true; return key + '3'; }",
   "    if(pet.C < C_FORM_BAD){ pet.formWild = true; return key + '3'; }", 'caught'],
  ['恨みの線が低すぎて、たまに起こしただけでとげとげになる',
   "  const M_FORM_BAD   = 70;", "  const M_FORM_BAD   = 20;", 'caught'],
  ['すらりの「ケアだけ」の道が無くなる',
   "    if(pet.C >= C_FORM_SLEEK) return key + '2';                          // ケアだけで極めた",
   "    if(false) return key + '2';                                          // ケアだけで極めた", 'caught'],
  ['すらりの「ゲームだけ」の道が無くなる',
   "    if(allRounder()) return key + '2';                                   // ゲームだけで極めた",
   "    if(false) return key + '2';                                          // ゲームだけで極めた", 'caught'],
  ['すらりの「両方そこそこ」の道が無くなる',
   "    if(pet.C >= C_FORM_GOOD && allRounderSoft()) return key + '2';       // 両方そこそこ",
   "    if(false) return key + '2';                                          // 両方そこそこ", 'caught'],
  ['ゆるいほうの線が単独ルートと同じになる（併用の意味が無くなる）',
   "  const ALLROUND_SOFT = { sw: 400, ss: 450, ab: 250 };",
   "  const ALLROUND_SOFT = { sw: 600, ss: 700, ab: 400 };", 'caught'],
  ['ゆるい線が3本そろわなくても通る',
   "    return (b.sw||0) >= ALLROUND_SOFT.sw && (b.ss||0) >= ALLROUND_SOFT.ss && (b.ab||0) >= ALLROUND_SOFT.ab; }",
   "    return (b.sw||0) >= ALLROUND_SOFT.sw || (b.ss||0) >= ALLROUND_SOFT.ss || (b.ab||0) >= ALLROUND_SOFT.ab; }", 'caught'],
  ['育ちきらなかった子が帰還ではなく家出になる（世話はしていたのに）',
   "      pet.homeFlag = true; pet.homeRedeem = false;\n      addDiary({ d: petDay(), n: pet.name, t: ['broughtHome'], v: [voiceIdx()], c: '', ts: Date.now(), cd: todayKey() });",
   "      pet.ufoFlag = true;\n      addDiary({ d: petDay(), n: pet.name, t: ['farewell'], v: [voiceIdx()], c: '', ts: Date.now(), cd: todayKey() });", 'caught'],
  ['とげとげが立て直しても帰還にならない',
   "        else if(redeemed()){", "        else if(false){", 'caught'],
  ['とげとげが立て直さなくても帰還になる',
   "        else if(redeemed()){", "        else if(true){", 'caught'],
  ['立て直しに 世話の続きが要らなくなる',
   "    return (s.careStreak||0) >= REDEEM_DAYS && (s.M||0) < WRATH_HOLD; }",
   "    return (s.M||0) < WRATH_HOLD; }", 'caught'],
  ['立て直しに 恨みが薄れていることが要らなくなる',
   "    return (s.careStreak||0) >= REDEEM_DAYS && (s.M||0) < WRATH_HOLD; }",
   "    return (s.careStreak||0) >= REDEEM_DAYS; }", 'caught'],
  ['とげとげにも旅立ちが来てしまう',
   "      } else if(pet.B >= 60 && pet.health === 'GOOD'){\n        pet.departFlag = true;",
   "      }\n      if(pet.B >= 60 && pet.health === 'GOOD'){\n        pet.departFlag = true;", 'caught'],
  ['ほめる音と しかる音が入れかわる（良いことと良くないことが逆に聞こえる）',
   "    praise:  [[784,0.08],[988,0.08],[1319,0.18]],              // うれしい（ソ・シ・ミ）",
   "    praise:  [[784,0.08],[600,0.08],[440,0.18]],               // うれしい（ソ・シ・ミ）", 'caught'],
  ['くすりの音が下がる（効いた感じがしない）',
   "    med:     [[523,0.07],[659,0.07],[784,0.07],[1047,0.16]],   // 効いていく（ド・ミ・ソ・ド）",
   "    med:     [[1047,0.07],[784,0.07],[659,0.07],[523,0.16]],   // 効いていく（ド・ミ・ソ・ド）", 'caught'],
  ['グレイが横にならず 立ったまま寝る',
   "    g1: G_LIE.g1,                           // グレイ3種は仰向け\n    g2: G_LIE.g2,\n    g3: G_LIE.g3,",
   "    g1: lie(S4_SHUT.g1, 3),\n    g2: lie(S4_SHUT.g2, 3),\n    g3: lie(S4_SHUT.g3, 3),", 'caught'],
  ['成体グレイだけ 横にならない',
   "    grey: G_LIE.grey,                       // 成体グレイは仰向け",
   "    grey: lie(S3_SHUT.grey, 2),", 'caught'],
  ['グレイ4種が同じ寝姿になる（見分けがつかない）',
   "    g1: G_LIE.g1,                           // グレイ3種は仰向け\n    g2: G_LIE.g2,\n    g3: G_LIE.g3,",
   "    g1: G_LIE.g1,                           // グレイ3種は仰向け\n    g2: G_LIE.g1,\n    g3: G_LIE.g1,", 'caught'],
  ['グレイの首がちぎれて 頭と胴が離れる（2匹に見える）',
   "      [0,1,1,1,1,1,1,1,1,1,1,1,0,0],\n      [0,1,1,1,1,1,1,1,1,1,1,1,0,1],\n      [0,0,1,1,1,1,1,1,0,1,1,1,1,1],",
   "      [0,1,1,1,1,1,1,1,1,0,1,1,0,0],\n      [0,1,1,1,1,1,1,1,1,0,1,1,0,1],\n      [0,0,1,1,1,1,1,1,0,0,1,1,1,1],", 'caught'],
  ['グレイのとじた目が つぶれる（顔だけ正面を向いている）',
   "      [0,1,1,1,1,1,0,1,1,0,0,0,0,0],\n      [1,1,1,1,1,1,0,1,1,0,0,0,0,0],",
   "      [0,1,1,1,1,1,1,1,1,0,0,0,0,0],\n      [1,1,1,1,1,1,1,1,1,0,0,0,0,0],", 'caught'],
  ['グレイの寝姿が縦長のまま（横になって見えない）',
   "    grey: [                     // 成体グレイ  11×8\n      [0,0,1,1,1,1,0,0,0,0,0],",
   "    grey: [                     // 成体グレイ  11×8\n      [0,0,1,1,1,1,0,0],", 'caught'],
  ['病気の姿を 寝姿から作ってしまう（グレイだと体が入れ替わる）',
   "    const shut = sp.shut || sp.sleep;                  // 同上。グレイの寝姿は横向きなので使えない\n    const repl = eyeRows(sp).map(y => [y, shut[y]]);",
   "    const shut = sp.sleep;\n    const repl = [];\n    const n = Math.min(shut.length, sp.rest.length);\n    for(let y=0; y<n; y++){\n      if(sp.rest[y].length === shut[y].length &&\n         sp.rest[y].some((v,x)=>v !== shut[y][x])) repl.push([y, shut[y]]);\n    }",
   'caught'],
  ['目の段の割り出しに 寝姿を使う（グレイで目が動かなくなる）',
   "    const shut = sp.shut || sp.sleep;                  // 寝姿ではなく 正面の閉眼と見比べる",
   "    const shut = sp.sleep;", 'caught'],
  ['タコ系の足だけ畳まれない',
   "    t1: lie(S4_SHUT.t1, 2),\n    t2: lie(S4_SHUT.t2, 2),",
   "    t1: lie(S4_SHUT.t1, 1),\n    t2: lie(S4_SHUT.t2, 1),", 'caught'],
  ['インベーダー系の足だけ畳まれない',
   "    i1: lie(S4_SHUT.i1, 3),\n    i2: lie(S4_SHUT.i2, 3),",
   "    i1: lie(S4_SHUT.i1, 2),\n    i2: lie(S4_SHUT.i2, 2),", 'caught'],
  ['畳みすぎて 体まで削れる',
   "    i3: lie(S4_SHUT.i3, 3),",
   "    i3: lie(S4_SHUT.i3, 5),", 'caught'],
  ['寝姿が地面から浮く（背が縮んだぶん宙に描かれる）',
   "      const by = MAIN_GY - body.length;                      // 足元を地面に据える",
   "      const by = MAIN_GY - 14;                               // 足元を地面に据える", 'caught'],
  ['しつけ・甘やかしのタグを持ち回りの外に置く（この3つで枠を埋めてしまう）',
   "                                 'scoldedUnfair','taught','snackMany','woken',\n                                 'rhythmDay','rhythmNight','tantrum']);",
   "                                 ]);", 'caught'],
  ['しつけが通った日を日記に残さない',
   "          note('taught');                              // しつけが通った日。放置したわがままだけが",
   "                                                       // しつけが通った日。放置したわがままだけが", 'caught'],
  ['旧セーブの しかる の日記が読めなくなる',
   "  DIARY_LINES.scolded = DIARY_LINES.scoldedUnfair;", "", 'caught'],
  ['読まれずに落ちた話題まで「書いた」ことにする',
   "    e = trimToShown(e);", "", 'caught'],
  //  いまの文面では、いちばん長い話題(5行)でも 結び(最長2行)を引いた残り(5行)に収まるので、
  //  「1つも載らない」状態は作れない。この歯止めは、あとで長い文面を足した時のためのもの
  ['落ちた話題を消しすぎる（載ったぶんまで捨てる）',
   "    if(!keep.length || keep.length === e.t.length) return e;",
   "    if(keep.length === e.t.length) return e;", 'equivalent'],
  ['親密度を 記録の件数で割る（2日目で うちとけた になる）',
   "    const avg = log.reduce((a, b) => a + b, 0) / WARM_WINDOW;",
   "    const avg = log.length ? log.reduce((a, b) => a + b, 0) / log.length : 0;", 'caught'],
  ['重複よけの窓が 日記帳より短い（31日目に一巡する）',
   "  const DIARY_NOREPEAT_DAYS = DIARY_MAX;", "  const DIARY_NOREPEAT_DAYS = 30;", 'caught'],
  ['オープニングの受けつけ判定が ゆるくなる（演出中でも押せる）',
   "  function openingLocked(){ return !!manualFrame || !openingReady; }",
   "  function openingLocked(){ return !!manualFrame; }", 'caught'],
  ['A だけ 演出中でも効いてしまう',
   "    if(openingLocked()) return;                   // 演出のあいだは押せない",
   "    if(manualFrame) return;", 'caught'],
  ['止める前に音を鳴らす（効いたように聞こえる）',
   "    if(openingLocked()) return;                   // 演出のあいだは押せない\n    playClick(); btnAnim(document.getElementById('oa'));",
   "    playClick(); btnAnim(document.getElementById('oa'));\n    if(openingLocked()) return;", 'caught'],
  ['幕引きに通し上限が無い（手をかけない人ほど長く一緒にいられる）',
   "    const byAll  = s.lineageAt ? s.lineageAt + FINAL_CAP * 86400000 : Infinity;",
   "    const byAll  = Infinity;", 'caught'],
  ['通し上限が短くて、甘やかしが最終形態を満喫できない',
   "  const FINAL_CAP       = 30;", "  const FINAL_CAP       = 20;", 'caught'],
  ['なかよしが届かない子に迎えが来ない（行き止まりが戻る）',
   "      } else {\n        // 最終形態にはなったが、なかよしが旅立ちの線に届かなかった／病気のまま。",
   "      } else if(false) {\n        // 最終形態にはなったが、なかよしが旅立ちの線に届かなかった／病気のまま。", 'caught'],
  ['届かない子まで旅立たせてしまう（なかよしの線が無くなる）',
   "      } else if(pet.B >= 60 && pet.health === 'GOOD'){",
   "      } else if(true){", 'caught'],
  ['更新した瞬間に幕引きが来る（育っている子に猶予が無い）',
   "    3(p){ if(p.stage === 'final' && p.finalAt && Date.now() >= finalDue(p)) p.endGrace = Date.now() + END_GRACE_MS; },",
   "    3(p){ },", 'caught'],
  ['猶予を無視して幕引きする',
   "       !pet.invadeFlag && !pet.departFlag && now >= (pet.endGrace||0) && now >= finalDue()){",
   "       !pet.invadeFlag && !pet.departFlag && now >= finalDue()){", 'caught'],
  ['うまれたては日記を書かないように戻す',
   "  function diaryWriting(){ return !!pet.name && !!pet.stage; }",
   "  function diaryWriting(){ return !!pet.name && pet.stage !== 'egg'; }", 'caught'],
  ['名前をつける前から日記を書いてしまう',
   "  function diaryWriting(){ return !!pet.name && !!pet.stage; }",
   "  function diaryWriting(){ return !!pet.stage; }", 'caught'],
  ['くすりが左から飛んでくる（前の向きに戻る）',
   "  const MED_FROM  = W + 5;   // 飛び出す x（右の画面外）",
   "  const MED_FROM  = -5;      // 飛び出す x（右の画面外）", 'caught'],
  ['飛んでくる薬が、ただの丸になる（何が来たのか読めない）',
   "  const MED_PILL = [\n    [0,0,0,0,0,2,2,2,0],\n    [0,0,0,0,2,1,1,1,2],\n    [0,0,0,2,1,1,1,1,2],\n    [0,0,2,2,1,1,1,1,2],\n    [0,2,0,0,2,1,1,2,0],\n    [0,2,0,0,0,2,2,0,0],\n    [0,2,0,0,0,2,0,0,0],\n    [0,0,2,2,0,0,0,0,0],\n  ];",
   "  const MED_PILL = [\n    [0,2,2,2,2,2,2,2,0],\n    [2,2,1,1,1,1,1,2,2],\n    [2,1,1,1,1,1,1,1,2],\n    [2,1,1,1,1,1,1,1,2],\n    [2,1,1,1,1,1,1,1,2],\n    [2,1,1,1,1,1,1,1,2],\n    [2,2,1,1,1,1,1,2,2],\n    [0,2,2,2,2,2,2,2,0],\n  ];", 'caught'],
  ['飛んでくる薬が小さすぎる（形が読めない）',
   "  const MED_PILL = [\n    [0,0,0,0,0,2,2,2,0],\n    [0,0,0,0,2,1,1,1,2],\n    [0,0,0,2,1,1,1,1,2],\n    [0,0,2,2,1,1,1,1,2],\n    [0,2,0,0,2,1,1,2,0],\n    [0,2,0,0,0,2,2,0,0],\n    [0,2,0,0,0,2,0,0,0],\n    [0,0,2,2,0,0,0,0,0],\n  ];",
   "  const MED_PILL = [\n    [0,2,2,2],\n    [2,1,1,2],\n    [2,2,2,0],\n  ];", 'caught'],
  ['ふだんの話題を優先度の上から採る（毎日おなじ顔ぶれが並ぶ）',
   "    const picked = pickTopics(d, room);",
   "    const picked = DIARY_PRIORITY.filter(t => d[t] > 0).slice(0, room);", 'caught'],
  ['話題の持ち回りで、同着をいつも優先度順で解く（上のタグが毎日出る）',
   "      .map(t => [t, (at[t] == null ? -999 : at[t]) + Math.random()])   // 同着は散らす",
   "      .map(t => [t, (at[t] == null ? -999 : at[t])])", 'caught'],
  ['久しく書いていない順ではなく、最近書いた順に採る',
   "      .sort((a, b) => a[1] - b[1]).map(x => x[0]);",
   "      .sort((a, b) => b[1] - a[1]).map(x => x[0]);", 'caught'],
  ['重要な出来事まで持ち回りに混ぜる（進化や病気が後回しになる）',
   "    return fired.filter(t => !DIARY_ROUTINE.has(t)).concat(routine).slice(0, room);",
   "    return routine.concat(fired.filter(t => !DIARY_ROUTINE.has(t))).slice(0, room);", 'caught'],
  ['同じ言い回しを避ける窓が短くなる（育成の途中で戻ってくる）',
   "  const DIARY_NOREPEAT_DAYS = DIARY_MAX;", "  const DIARY_NOREPEAT_DAYS = 3;", 'caught'],
  ['親密度を見ずに言い回しを選ぶ（関係が文面に出ない）',
   "    const v = picked.map(t => pickFresh(warmCands(DIARY_LINES[t]), i => 't:' + t + ':' + i, used));",
   "    const v = picked.map(t => pickFresh(DIARY_LINES[t].map((_, i) => i), i => 't:' + t + ':' + i, used));", 'caught'],
  ['結びが親密度を見なくなる',
   "    const cv = c ? pickFresh(warmCands(DIARY_CLOSE[c]), i => 'c:' + c + ':' + i, used) : 0;",
   "    const cv = c ? pickFresh(DIARY_CLOSE[c].map((_, i) => i), i => 'c:' + c + ':' + i, used) : 0;", 'caught'],
  ['親密度に ごはん・そうじ を数えてしまう',
   "    (pet.touchLog || (pet.touchLog = [])).push(touches);",
   "    (pet.touchLog || (pet.touchLog = [])).push(touches + (d.fed ? 1 : 0) + (d.cleaned ? 1 : 0));", 'caught'],
  ['親密度の窓を切らない（際限なく貯まって、離れても下がらない）',
   "    if(pet.touchLog.length > WARM_WINDOW) pet.touchLog.splice(0, pet.touchLog.length - WARM_WINDOW);",
   "", 'caught'],
  ['親密度が なかよし度だけで決まる（直近の関わりが効かない）',
   "    return near * (1 - WARM_B_MIX) + bond * WARM_B_MIX;",
   "    return bond;", 'caught'],
  ['親密度の段階が いつも いちばん上になる',
   "    return w < WARM_LINE[0] ? 0 : (w < WARM_LINE[1] ? 1 : 2);",
   "    return 2;", 'caught'],
  ['ひとりごとが親密度を見なくなる',
   "      warm:  warmLevel(),                 // 0=よそよそしい 1=なじんだ 2=うちとけた",
   "      warm:  0,", 'caught'],
  ['鳥が飛ばなくなる',
   "      if (weather === 'clear') updateBirds(DM);", "", 'caught'],
  ['鳥が薄曇りでも飛ぶ（晴れの特別感が薄れる）',
   "      if (weather === 'clear') updateBirds(DM);", "      updateBirds(DM);", 'caught'],
  ['胴が太くなる（1ドットでなくなる）',
   "  const BIRD_UP = [                      // 翼を上げた形\n    [1,0,0,0,1],                         //  翼の先\n    [0,1,0,1,0],                         //  翼の内側\n    [0,0,1,0,0],                         //  胴は1ドット。ここは動かさない\n    [0,0,0,0,0],\n    [0,0,0,0,0],\n  ];",
   "  const BIRD_UP = [                      // 翼を上げた形\n    [1,0,0,0,1],\n    [0,1,0,1,0],\n    [0,1,1,1,0],\n    [0,0,0,0,0],\n    [0,0,0,0,0],\n  ];", 'caught'],
  ['翼が片側1ドットになる',
   "  const BIRD_UP = [                      // 翼を上げた形\n    [1,0,0,0,1],                         //  翼の先\n    [0,1,0,1,0],                         //  翼の内側\n    [0,0,1,0,0],                         //  胴は1ドット。ここは動かさない\n    [0,0,0,0,0],\n    [0,0,0,0,0],\n  ];",
   "  const BIRD_UP = [                      // 翼を上げた形\n    [0,0,0,0,0],\n    [0,1,0,1,0],\n    [0,0,1,0,0],\n    [0,0,0,0,0],\n    [0,0,0,0,0],\n  ];", 'caught'],
  ['翼の2ドットが水平に並ぶ（棒に見える）',
   "  const BIRD_UP = [                      // 翼を上げた形\n    [1,0,0,0,1],                         //  翼の先\n    [0,1,0,1,0],                         //  翼の内側\n    [0,0,1,0,0],                         //  胴は1ドット。ここは動かさない\n    [0,0,0,0,0],\n    [0,0,0,0,0],\n  ];",
   "  const BIRD_UP = [                      // 翼を上げた形\n    [0,0,0,0,0],\n    [1,1,0,1,1],\n    [0,0,1,0,0],\n    [0,0,0,0,0],\n    [0,0,0,0,0],\n  ];", 'caught'],
  ['翼の先が内側より内へ入る（形が反る）',
   "    [1,0,0,0,1],                         //  翼の先\n    [0,1,0,1,0],                         //  翼の内側",
   "    [0,1,0,1,0],                         //  翼の先\n    [1,0,0,0,1],                         //  翼の内側", 'caught'],
  ['鳥がはばたかない（2コマが同じ形）',
   "  const BIRD_DOWN = [                    // 下げた形\n    [0,0,0,0,0],\n    [0,0,0,0,0],\n    [0,0,1,0,0],                         //  胴（上と同じ段）\n    [0,1,0,1,0],\n    [1,0,0,0,1],\n  ];",
   "  const BIRD_DOWN = [                    // 下げた形\n    [1,0,0,0,1],\n    [0,1,0,1,0],\n    [0,0,1,0,0],\n    [0,0,0,0,0],\n    [0,0,0,0,0],\n  ];", 'caught'],
  ['鳥の胴も一緒に上下する（羽ばたきに見えない）',
   "  const BIRD_DOWN = [                    // 下げた形\n    [0,0,0,0,0],\n    [0,0,0,0,0],\n    [0,0,1,0,0],                         //  胴（上と同じ段）\n    [0,1,0,1,0],\n    [1,0,0,0,1],\n  ];",
   "  const BIRD_DOWN = [                    // 下げた形\n    [0,0,0,0,0],\n    [0,0,0,0,0],\n    [0,0,0,0,0],\n    [0,1,0,1,0],\n    [1,0,1,0,1],\n  ];", 'caught'],
  ['鳥が点に戻る（翼を振る余地がない）',
   "  const BIRD_UP = [                      // 翼を上げた形\n    [1,0,0,0,1],                         //  翼の先\n    [0,1,0,1,0],                         //  翼の内側\n    [0,0,1,0,0],                         //  胴は1ドット。ここは動かさない\n    [0,0,0,0,0],\n    [0,0,0,0,0],\n  ];",
   "  const BIRD_UP = [                      // 翼を上げた形\n    [1,0,1],\n    [0,1,0],\n  ];", 'caught'],
  ['鳥が遠ざかっても小さくならない',
   "birdSprite(birds.t, birds.x < W * BIRD_FAR_X)", "birdSprite(birds.t, false)", 'caught'],
  ['鳥が最初から小さい（近づいてくる感じになる）',
   "birdSprite(birds.t, birds.x < W * BIRD_FAR_X)", "birdSprite(birds.t, true)", 'caught'],
  ['小さくなる時に胴の位置がずれる（縮んだ拍子に跳ねる）',
   "    return { spr, dx: bodyN - body, dy: rowN - row };",
   "    return { spr, dx: 0, dy: 0 };", 'caught'],
  ['遠くの鳥もはばたかない（2コマが同じ）',
   "  const BIRD_FAR_DOWN = [\n    [0,0,0],\n    [0,1,0],                             //  胴（上と同じ段）\n    [1,0,1],\n  ];",
   "  const BIRD_FAR_DOWN = [\n    [1,0,1],\n    [0,1,0],\n    [0,0,0],\n  ];", 'caught'],
  ['遠くの鳥は胴ごと上下する',
   "  const BIRD_FAR_DOWN = [\n    [0,0,0],\n    [0,1,0],                             //  胴（上と同じ段）\n    [1,0,1],\n  ];",
   "  const BIRD_FAR_DOWN = [\n    [0,0,0],\n    [0,0,0],\n    [1,1,1],\n  ];", 'caught'],
  ['遠くの鳥の翼が減っていない（手前と同じ大きさ）',
   "  const BIRD_FAR_UP = [\n    [1,0,1],                             //  翼の先だけ\n    [0,1,0],                             //  胴\n    [0,0,0],\n  ];",
   "  const BIRD_FAR_UP = [\n    [1,0,0,0,1],\n    [0,1,1,1,0],\n    [0,0,0,0,0],\n  ];", 'caught'],
  ['切り替えが端に寄る（ずっと小さいまま／ずっと大きいまま）',
   "  const BIRD_FAR_X = 0.5;                // 画面のこの割合より左へ行ったら遠ざかった形",
   "  const BIRD_FAR_X = 1.5;                // 画面のこの割合より左へ行ったら遠ざかった形", 'caught'],
  ['鳥が1羽になる',
   "  const BIRD_GAP   = [[0,0],[7,2]];   // 2羽の位置ずれ [x, y]。翼を広げたぶん離す",
   "  const BIRD_GAP   = [[0,0]];         // 2羽の位置ずれ [x, y]。翼を広げたぶん離す", 'caught'],
  ['2羽が重なる（翼の幅より近い）',
   "  const BIRD_GAP   = [[0,0],[7,2]];   // 2羽の位置ずれ [x, y]。翼を広げたぶん離す",
   "  const BIRD_GAP   = [[0,0],[2,2]];   // 2羽の位置ずれ [x, y]。翼を広げたぶん離す", 'caught'],
  ['花が咲かなくなる',
   "    if (!hideSky) drawFlowers(DM);", "", 'caught'],
  ['花が最初から全部咲いている（日々の変化が伝わらない）',
   "    if(d < 0) return 0;\n    return Math.min(FLOWERS.length, Math.round((d + 1) / FLOWER_SPAN * FLOWERS.length));",
   "    return FLOWERS.length;", 'caught'],
  ['花が咲きそろわない（5日たっても増え切らない）',
   "  const FLOWER_SPAN = 5;      // 咲きそろうまでの日数",
   "  const FLOWER_SPAN = 40;     // 咲きそろうまでの日数", 'caught'],
  ['花が20日より前から咲く',
   "  const FLOWER_DAY  = 20;     // 咲き始める日",
   "  const FLOWER_DAY  = 1;      // 咲き始める日", 'caught'],
  ['花がキャラの手前に描かれる（キャラを覆う）',
   "    // 地面の花（20日目から少しずつ増える）。背景の一部なので、キャラはこの前を歩く\n    if (!hideSky) drawFlowers(DM);\n  }",
   "  }", 'caught'],
  ['花が皿の帯に咲く（皿に隠れっぱなしになる）',
   "    [26,0], [15,1], [3,2],  [51,0],",
   "    [26,0], [15,1], [3,2],  [40,0],", 'caught'],
  ['花が左から順に咲く（端から埋まって見える）',
   "    [20,2], [33,0], [9,2],  [47,1],\n    [26,0], [15,1], [3,2],  [51,0],",
   "    [3,2],  [9,2],  [15,1], [20,2],\n    [26,0], [33,0], [47,1], [51,0],", 'caught'],
  ['花の背丈がそろってしまう（並木のように見える）',
   "    [20,2], [33,0], [9,2],  [47,1],\n    [26,0], [15,1], [3,2],  [51,0],",
   "    [20,2], [33,2], [9,2],  [47,2],\n    [26,2], [15,2], [3,2],  [51,2],", 'caught'],
  ['咲いた花の中心が埋まる（プラス記号に見える）',
   "      [0,1,0],\n      [1,0,1],\n      [0,1,0],\n      [0,1,0],\n      [0,1,0],",
   "      [0,1,0],\n      [1,1,1],\n      [0,1,0],\n      [0,1,0],\n      [0,1,0],", 'caught'],
  ['双葉が咲いた花と同じ背丈になる（育ち具合が伝わらない）',
   "    [                       // 0：双葉。まだ咲いていないので背が低い\n      [1,0,1],\n      [0,1,0],\n      [0,1,0],\n    ],",
   "    [                       // 0：双葉。まだ咲いていないので背が低い\n      [1,0,1],\n      [0,1,0],\n      [0,1,0],\n      [0,1,0],\n      [0,1,0],\n    ],", 'caught'],
  ['雷雨がただの雨になる（嵐が消える）',
   "    if ([95,96,99].includes(code))                         return 'storm';", "", 'caught'],
  ['大雨が雨と同じ見た目になる',
   "    if ([55,65,82].includes(code))                         return 'rainHeavy';", "", 'caught'],
  ['大雪が雪と同じ見た目になる',
   "    if ([75,86].includes(code))                            return 'snowHeavy';", "", 'caught'],
  ['薄曇りが無くなる（曇り扱いになって天体が消える）',
   "    if (code === 2)                                        return 'thin';", "", 'caught'],
  ['薄曇りがゲームでも曇り扱いになる（影響が変わる）',
   "    clear:'clear', thin:'clear', cloudy:'cloudy',",
   "    clear:'clear', thin:'cloudy', cloudy:'cloudy',", 'caught'],
  ['大雨・嵐の影響が雨より重くなる（現状維持のはずが変わる）',
   "    rain:'rain', rainHeavy:'rain', storm:'rain',",
   "    rain:'rain', rainHeavy:'snow', storm:'snow',", 'caught'],
  ['嵐の横なぐりが無くなる',
   "    storm:     { n:24, spd:2.2, len:4, slant:2 },   // 横なぐり：1段下がるごとに slant ドット横へ",
   "    storm:     { n:24, spd:2.2, len:4, slant:0 },   // 横なぐり：1段下がるごとに slant ドット横へ", 'caught'],
  ['大雨が雨より薄くなる',
   "    rainHeavy: { n:18, spd:1.7, len:4, slant:0 },",
   "    rainHeavy: { n:6,  spd:0.8, len:4, slant:0 },", 'caught'],
  ['大雪が雪より薄くなる',
   "  const SNOW_STYLE = { snow: { n:16, spd:1.0 }, snowHeavy: { n:30, spd:1.6 } };",
   "  const SNOW_STYLE = { snow: { n:16, spd:1.0 }, snowHeavy: { n:8, spd:0.6 } };", 'caught'],
  ['薄曇りで天体が隠れる',
   "    const skyOpen = (weather === 'clear' || weather === 'thin');",
   "    const skyOpen = (weather === 'clear');", 'caught'],
  ['曇りでも天体が見える（薄曇りと区別がつかない）',
   "    const skyOpen = (weather === 'clear' || weather === 'thin');",
   "    const skyOpen = (weather === 'clear' || weather === 'thin' || weather === 'cloudy');", 'caught'],
  ['薄曇りの雲が曇りと同じ量になる',
   "  const CLOUD_THIN = 2;   // 薄曇り：天体は見えたまま、雲は控えめ",
   "  const CLOUD_THIN = 6;   // 薄曇り：天体は見えたまま、雲は控えめ", 'caught'],
  ['押し出しが歩行の中に戻る（寝ている子がうんちに重なったままになる）',
   "    pushOutOfObjects(gw);", "", 'caught'],
  ['押し出しが効かない（重なっていても動かない）',
   "    if(segs.some(([a,b]) => walkX >= a && walkX <= b)) return;   // もう重なっていない",
   "    return;", 'caught'],
  ['押し出しが一気に飛ぶ（瞬間移動して見える）',
   "    walkX += Math.sign(target - walkX) * Math.min(0.8, Math.abs(target - walkX));\n  }\n  // 幅gwのキャラ左端xを置ける自由区間（画面内・障害物を除く）",
   "    walkX = target;\n  }\n  // 幅gwのキャラ左端xを置ける自由区間（画面内・障害物を除く）", 'caught'],
  ['重なっていない子まで押し出す（うろうろして落ち着かない）',
   "    if(segs.some(([a,b]) => walkX >= a && walkX <= b)) return;   // もう重なっていない",
   "    if(false) return;   // もう重なっていない", 'caught'],
  ['そうじのキラキラが鳴らなくなる',
   "  const REACT_SND = { heart:'praise', anger:'anger', sad:'sad', refuse:'tantrum', clean:'sparkle' };",
   "  const REACT_SND = { heart:'praise', anger:'anger', sad:'sad', refuse:'tantrum' };", 'caught'],
  ['キラキラが低い音域で鳴る（そうじが晴れやかに聞こえない）',
   "    sparkle: [[1568,0.06,0.09],[2093,0.09,0.09],[0,0.09],\n              [1760,0.06,0.09],[2349,0.09,0.09],[0,0.09],\n              [1976,0.06,0.09],[2349,0.06,0.09],[2637,0.45,0.10]],",
   "    sparkle: [[196,0.06,0.09],[247,0.09,0.09],[0,0.09],[220,0.06,0.09],[262,0.45,0.10]],", 'caught'],
  ['キラキラが点に戻る（見た目の3秒に対して短すぎる）',
   "    sparkle: [[1568,0.06,0.09],[2093,0.09,0.09],[0,0.09],\n              [1760,0.06,0.09],[2349,0.09,0.09],[0,0.09],\n              [1976,0.06,0.09],[2349,0.06,0.09],[2637,0.45,0.10]],",
   "    sparkle: [[1568,0.03,0.09],[1976,0.07,0.09]],", 'caught'],
  ['キラキラの区切りが無くなる（キラキラキランに聞こえない）',
   "    sparkle: [[1568,0.06,0.09],[2093,0.09,0.09],[0,0.09],\n              [1760,0.06,0.09],[2349,0.09,0.09],[0,0.09],\n              [1976,0.06,0.09],[2349,0.06,0.09],[2637,0.45,0.10]],",
   "    sparkle: [[1568,0.06,0.09],[2093,0.09,0.09],[1760,0.06,0.09],[2349,0.09,0.09],[1976,0.06,0.09],[2349,0.06,0.09],[2637,0.45,0.10]],", 'caught'],
  ['キラキラの最後が伸びない（ンッ が無い）',
   "    sparkle: [[1568,0.06,0.09],[2093,0.09,0.09],[0,0.09],\n              [1760,0.06,0.09],[2349,0.09,0.09],[0,0.09],\n              [1976,0.06,0.09],[2349,0.06,0.09],[2637,0.45,0.10]],",
   "    sparkle: [[1568,0.45,0.09],[2093,0.09,0.09],[0,0.09],[1760,0.06,0.09],[2349,0.09,0.09],[0,0.09],[1976,0.06,0.09],[2349,0.06,0.09],[2637,0.06,0.10]],", 'caught'],
  ['静かに片づけたい時にも音が鳴る（寝ている子・拒んだ皿）',
   "    const snd = quiet ? null : REACT_SND[type];",
   "    const snd = REACT_SND[type];", 'caught'],
  ['イライラの音が上がる（怒っているように聞こえない）',
   "    anger:   [[311,0.045],[220,0.05],[165,0.14]],              // イライラ（低いところへ転げ落ちる。着地はいちばん低い）",
   "    anger:   [[165,0.045],[220,0.05],[311,0.14]],              // イライラ（低いところへ転げ落ちる。着地はいちばん低い）", 'caught'],
  ['イライラが高い音域で鳴る（明るく聞こえる）',
   "    anger:   [[311,0.045],[220,0.05],[165,0.14]],              // イライラ（低いところへ転げ落ちる。着地はいちばん低い）",
   "    anger:   [[1244,0.045],[880,0.05],[660,0.14]],             // イライラ（低いところへ転げ落ちる。着地はいちばん低い）", 'caught'],
  ['しゅんの音が上がる（受け入れたように聞こえない）',
   "    sad:     [[247,0.10,0.10],[196,0.12,0.10],[175,0.30,0.10]], // しゅん（3段でうなだれる。最後は全音だけ下げて、ため息のように落とす）",
   "    sad:     [[175,0.10,0.10],[196,0.12,0.10],[247,0.30,0.10]], // しゅん（3段でうなだれる。最後は全音だけ下げて、ため息のように落とす）", 'caught'],
  ['しゅんがイライラと同じ強さで鳴る（手ざわりが分かれない）',
   "    sad:     [[247,0.10,0.10],[196,0.12,0.10],[175,0.30,0.10]], // しゅん（3段でうなだれる。最後は全音だけ下げて、ため息のように落とす）",
   "    sad:     [[247,0.10],[196,0.12],[175,0.30]],                // しゅん（3段でうなだれる。最後は全音だけ下げて、ため息のように落とす）", 'caught'],
  ['しゅんが2音に戻る（うなだれる段が減る）',
   "    sad:     [[247,0.10,0.10],[196,0.12,0.10],[175,0.30,0.10]], // しゅん（3段でうなだれる。最後は全音だけ下げて、ため息のように落とす）",
   "    sad:     [[247,0.10,0.10],[196,0.30,0.10]],                // しゅん", 'caught'],
  ['しゅんが高い音域で鳴る（明るく聞こえる）',
   "    sad:     [[247,0.10,0.10],[196,0.12,0.10],[175,0.30,0.10]], // しゅん（3段でうなだれる。最後は全音だけ下げて、ため息のように落とす）",
   "    sad:     [[988,0.10,0.10],[784,0.12,0.10],[698,0.30,0.10]], // しゅん（3段でうなだれる。最後は全音だけ下げて、ため息のように落とす）", 'caught'],
  ['ひと口の音が長すぎて、次の口に重なる',
   "    bite:    [[300,0.05],[210,0.05]],                          // ひと口ぶん。食事アニメの3口に合わせて3回鳴らす",
   "    bite:    [[300,1.00],[210,1.00]],                          // ひと口ぶん。食事アニメの3口に合わせて3回鳴らす", 'caught'],
  ['わがままの音が高くなる（うれしそうに聞こえる）',
   "    tantrum: [[220,0.09],[180,0.09],[220,0.09],[180,0.14]],     // いやいや（低く揺れる）",
   "    tantrum: [[1220,0.09],[1180,0.09],[1220,0.09],[1180,0.14]], // いやいや（低く揺れる）", 'caught'],
  ['たべる音が鳴らなくなる',
   "        if(biteFrame(reactT)) playSnd('bite');", "", 'caught'],
  ['たべる音が押した時にまとめて鳴る（絵と噛み合わない）',
   "    return el >= EAT_STEP && el % EAT_STEP === 0;",
   "    return el === 0;", 'caught'],
  ['たべる音が毎コマ鳴る',
   "    return el >= EAT_STEP && el % EAT_STEP === 0;",
   "    return el >= EAT_STEP;", 'caught'],
  ['たべる音の間隔が皿の減りとずれる',
   "  const EAT_STEP = 15;       // ひと口ぶんの間隔（1.5秒）。皿の減りと音の両方がこれを見る",
   "  const EAT_STEP = 7;        // ひと口ぶんの間隔（1.5秒）。皿の減りと音の両方がこれを見る", 'caught'],
  ['仕草の音が鳴らなくなる（ほめても叱っても無音）',
   "    const snd = quiet ? null : REACT_SND[type];\n    if(snd) playSnd(snd);", "", 'caught'],
  ['しゅんとイライラが同じ音になる（通ったか失敗したか分からない）',
   "  const REACT_SND = { heart:'praise', anger:'anger', sad:'sad', refuse:'tantrum', clean:'sparkle' };",
   "  const REACT_SND = { heart:'praise', anger:'anger', sad:'anger', refuse:'tantrum', clean:'sparkle' };", 'caught'],
  ['くすりが当たる手前で消える（着弾に届かない割り算に戻す）',
   "    const p = t / (MED_FLY - 1);                       // 0→1",
   "    const p = t / MED_FLY;                             // 0→1", 'caught'],
  ['くすりの弧が無くなって、まっすぐ飛ぶ',
   "  const MED_ARC   = 14;      // 放物線の高さ（ドット）",
   "  const MED_ARC   = 0;       // 放物線の高さ（ドット）", 'caught'],
  ['くすりが画面の中から湧く（飛んでくるように見えない）',
   "  const MED_FROM  = W + 5;   // 飛び出す x（右の画面外）",
   "  const MED_FROM  = 12;      // 飛び出す x（右の画面外）", 'caught'],
  ['くすりの点滅が無くなる（効いたのが分からない）',
   "  const MED_BLINK = 26;      // 当たってから点滅している時間",
   "  const MED_BLINK = 0;       // 当たってから点滅している時間", 'caught'],
  ['帰還の2つの入口が、おもいでで同じ一文になる',
   "    if(pet.goneBy === 'redeem') return T('endRedeem');", "", 'caught'],
  ['立て直しで帰っても、時間切れとして記録される',
   "      pet.gone = true; pet.goneBy = pet.homeRedeem ? 'redeem' : 'home'; pet.homeFlag = false;",
   "      pet.gone = true; pet.goneBy = 'home'; pet.homeFlag = false;", 'caught'],
  ['立て直しの印が立たない（おもいでが時間切れの文になる）',
   "        pet.homeFlag = true; pet.homeRedeem = true;",
   "        pet.homeFlag = true; pet.homeRedeem = false;", 'caught'],
  ['旅立ちの「また いつか あおう」が無くなる',
   "'そだててくれて ありがとう','また いつか あおう'],\n                  en:['THEY CAME FOR ME.','I CAN MANAGE NOW.','THANK YOU FOR','RAISING ME','UNTIL WE MEET AGAIN.'] },",
   "'そだててくれて ありがとう'],\n                  en:['THEY CAME FOR ME.','I CAN MANAGE NOW.','THANK YOU FOR','RAISING ME'] },", 'caught'],
  ['家出のあとの画面に GOODBYE... が戻る（だまって出ていったのに言葉が出る）',
   "    const msg = pet.goneBy==='depart' ? 'THANK YOU!' : (pet.goneBy==='invade' ? 'GAME OVER...' : '');",
   "    const msg = pet.goneBy==='depart' ? 'THANK YOU!' : (pet.goneBy==='return' ? 'GOODBYE...' : (pet.goneBy==='invade' ? 'GAME OVER...' : ''));", 'caught'],
  ['家出の日記が「むかえが きた」に戻る（演出は自分で歩いて出ていくのに）',
   "    farewell: [ { ja:['ばいばい'],   en:['BYE BYE.'] },",
   "    farewell: [ { ja:['むかえが きた'],   en:['THEY CAME FOR ME.'] },", 'caught'],
  ['とげとげの家出の日記が「むかえが きた」に戻る',
   "    farewellWild:[{ ja:['でていく','じゃあな'],       en:['I AM LEAVING.','GOODBYE.'] },",
   "    farewellWild:[{ ja:['むかえが きた','じゃあな'],       en:['THEY CAME FOR ME.','GOODBYE.'] },", 'caught'],
  ['旅立ちの日記から「むかえ」が消える（本当に迎えが来る側なのに）',
   "    departed: [ { ja:['むかえが きた','もう ひとりでも','だいじょうぶ','そだててくれて ありがとう','また いつか あおう'],",
   "    departed: [ { ja:['ひとりで いくよ','もう ひとりでも','だいじょうぶ','そだててくれて ありがとう','また いつか あおう'],", 'caught'],
  ['別れの言葉が枠からはみ出す長さになる',
   "                { ja:['でていくぞ','じゃあな'],     en:['I AM LEAVING.','SO LONG.'] } ],",
   "                { ja:['でていくぞ','じゃあな'],     en:['I AM LEAVING OUT OF HERE FOR GOOD.','SO LONG.'] } ],", 'caught'],
  ['睡眠妨害で しつけが減らなくなる（起こして遊ぶのが無傷になる）',
   "          addD(-4);                                                 // 不当なしかると同じだけ しつけも損なう。",
   "          addD(0);                                                  // 不当なしかると同じだけ しつけも損なう。", 'caught'],
  ['睡眠妨害で なかよしが減らなくなる',
   "          pet.B = Math.max(0, pet.B - 2);\n          addD(-4);                                                 // 不当なしかると同じだけ しつけも損なう。",
   "          addD(-4);                                                 // 不当なしかると同じだけ しつけも損なう。", 'caught'],
  ['睡眠妨害が 不当なしかると同じ重さになる（起こすほうが軽くなる）',
   "          addM(M_ADJ.wokenUp);                                      //  不当なしかるの上位版という位置づけ",
   "          addM(M_ADJ.scoldBad);                                     //  不当なしかるの上位版という位置づけ", 'caught'],
  ['不当なしかるで しゅんとしてしまう（叱り損ねが成功に見える）',
   "          addA(A_ADJ.scoldBad); note('scoldedUnfair');\n          //  しゅん（sad）は しつけが通った時だけの反応にしてある。\n          //  身に覚えのない叱られ方には怒る（睡眠妨害と同じ）\n          setReaction('anger');",
   "          addA(A_ADJ.scoldBad); note('scoldedUnfair');\n          setReaction('sad');", 'caught'],
  ['わがままを叱った時に 怒られてしまう（しつけが通ったのに伝わらない）',
   "          note('taught');                              // しつけが通った日。放置したわがままだけが\n          setReaction('sad');                          //  日記に残る、という非対称をなくす",
   "          note('taught');                              // しつけが通った日。放置したわがままだけが\n          setReaction('anger');                        //  日記に残る、という非対称をなくす", 'caught'],
  ['しつけの上限を90に戻す（しつけ単独ではグレイに届かなくなる）',
   "  const LINEAGE_D_FULL = 72;", "  const LINEAGE_D_FULL = 90;", 'caught'],
  ['しつけの下限をなくす（雑に叱ってもグレイに寄る）',
   "  const LINEAGE_D_MIN  = 55;", "  const LINEAGE_D_MIN  = 0;", 'caught'],
  ['世話の重みを主役にしてしまう（ゲームの偏りに勝ってしまう）',
   "  const LINEAGE_CARE_W = 0.45;", "  const LINEAGE_CARE_W = 1.2;", 'caught'],
  ['決め手なしの線をなくす（どれかに必ず寄ってしまう）',
   "  const LINEAGE_TH     = 0.30;", "  const LINEAGE_TH     = 0;", 'caught'],
  ['放置を系統に効かせてしまう（グレイ＝手抜きの結果になる）',
   "      inv:  playBias(r.ss),",
   "      inv:  playBias(r.ss) + LINEAGE_CARE_W * careStyle((pet.A||0) / Math.max(1, daysSince(pet.birth))).neglect / 100,", 'caught'],
  ['系統とミニゲームの対応を取り違える',
   "      tako: playBias(r.sw) + LINEAGE_CARE_W * spoil,",
   "      tako: playBias(r.ss) + LINEAGE_CARE_W * spoil,", 'caught'],
  ['しつけの代わりに甘やかしでグレイが決まる',
   "      grey: playBias(r.ab) + LINEAGE_CARE_W * discTrait(),",
   "      grey: playBias(r.ab) + LINEAGE_CARE_W * spoil,", 'caught'],
  ['成体で止まる期限を21日に戻す（週1休みの人が間に合わなくなる）',
   "  const STUCK_DAYS      = 28;", "  const STUCK_DAYS      = 21;", 'caught'],
  ['成体で止まる期限を極端に短くする',
   "  const STUCK_DAYS      = 28;", "  const STUCK_DAYS      = 3;", 'caught'],
  ['成体で止まる期限を実質なくす',
   "  const STUCK_DAYS      = 28;", "  const STUCK_DAYS      = 9999;", 'caught'],
  ['成体で止まった子に迎えが来なくなる',
   "    if(pet.stage==='adult' && pet.lineageAt && !pet.ufoFlag && !pet.homeFlag && !pet.invadeFlag &&\n       now - pet.lineageAt >= STUCK_DAYS*86400000){",
   "    if(false){", 'caught'],
  ['成体の期限が最終形態の子にも効いてしまう',
   "if(pet.stage==='adult' && pet.lineageAt && !pet.ufoFlag && !pet.homeFlag && !pet.invadeFlag &&",
   "if(pet.lineageAt && !pet.ufoFlag && !pet.homeFlag && !pet.invadeFlag &&", 'caught'],
  ['古いセーブの判定に、いまの基準を使ってしまう',
   "      return (b.sw||0) >= 250 && (b.ss||0) >= 100 && (b.ab||0) >= 400; }",
   "      return allRounder(q); }", 'caught'],
  ['入れ子の欠けたキーを埋めない',
   "    p.best  = Object.assign({sw:0, ss:0, ab:0}, sv.best);", '', 'caught'],
  ['にっきが1件も無いうちからメニューに並ぶ',
   "  function diaryUnlocked(){ return diaryLog.length > 0; }",
   "  function diaryUnlocked(){ return diaryWriting() || diaryLog.length > 0; }", 'caught'],
  ['にっきがメニューに並ばなくなる',
   "  function diaryUnlocked(){ return diaryLog.length > 0; }",
   "  function diaryUnlocked(){ return false; }", 'caught'],
  ['タイトルの選択肢の字が小さくなる（読めない）',
   "          ctxO.font = o.jp ? ('10px ' + JP_FONT) : '8px \"Press Start 2P\"';",
   "          ctxO.font = o.jp ? ('7px ' + JP_FONT) : '5px \"Press Start 2P\"';", 'caught'],
  ['アイコンから降りると右の列に着いてしまう',
   "          if(dir==='down')  menuSel = (r===0) ? menuSel+3 : topLeft;",
   "          if(dir==='down')  menuSel = (r===0) ? menuSel+3 : 6;", 'caught'],
  ['メニューが1列に戻る（読みものが右へ行かない）',
   "  const MENU_RIGHT = ['memory', 'story', 'manual'];", "  const MENU_RIGHT = [];", 'caught'],
  ['右の列に入れる項目をまちがえる',
   "  const MENU_RIGHT = ['memory', 'story', 'manual'];",
   "  const MENU_RIGHT = ['status', 'settings'];", 'caught'],
  ['おもいでが右の列に入らない（左が4行になる）',
   "  const MENU_RIGHT = ['memory', 'story', 'manual'];",
   "  const MENU_RIGHT = ['story', 'manual'];", 'caught'],
  ['列の振り分けで項目が抜け落ちる',
   "    list.forEach((it, i) => (MENU_RIGHT.includes(it[1]) ? right : left).push(i));",
   "    list.forEach((it, i) => { if(MENU_RIGHT.includes(it[1])) right.push(i); });", 'caught'],
  ['おばけになってもおもいでが開かない（死だけ抜ける）',
   "    if(++ghostT === GHOST_MEM_DELAY) endedShowMemory();", "", 'caught'],
  ['おばけになった瞬間におもいでが開く（おばけを見る間が無い）',
   "  const GHOST_MEM_DELAY = GHOST_STILL + GHOST_RISE_T + GHOST_HOLD;",
   "  const GHOST_MEM_DELAY = 1;", 'caught'],
  ['うずくまる間を置かず、いきなり魂が抜ける',
   "  const GHOST_STILL  = 10;", "  const GHOST_STILL  = 0;", 'caught'],
  ['魂が一瞬で昇りきる',
   "  const GHOST_RISE_T = 30;", "  const GHOST_RISE_T = 1;", 'caught'],
  ['昇りきってすぐ おもいで が開く',
   "  const GHOST_HOLD   = 8;", "  const GHOST_HOLD   = 0;", 'caught'],
  ['魂が昇りすぎてヘッダーに掛かる',
   "  const GHOST_Y_TOP  = 30;", "  const GHOST_Y_TOP  = 4;", 'caught'],
  ['魂がほとんど昇らない',
   "  const GHOST_Y_TOP  = 30;", "  const GHOST_Y_TOP  = 48;", 'caught'],
  ['体が薄れて消えない（うずくまったまま残る）',
   "      stampDust(body, bx, by, DM, 1 - dp, dp * GHOST_DUST_X);",
   "      stampDust(body, bx, by, DM, 1, dp * GHOST_DUST_X);", 'caught'],
  ['体が風で流されない（その場で薄れるだけ）',
   "  const GHOST_DUST_X = 12;", "  const GHOST_DUST_X = 0;", 'caught'],
  ['粒ごとの流れ方が同じで、砂埃にならない',
   "  function dustDrift(rx, ry){ return 0.4 + (dustHash(rx, ry) % 13) * 0.1; }",
   "  function dustDrift(rx, ry){ return 1; }", 'caught'],
  ['粒の飛び方が斜めにそろう（／／の筋が出る）',
   "  function dustDrift(rx, ry){ return 0.4 + (dustHash(rx, ry) % 13) * 0.1; }",
   "  function dustDrift(rx, ry){ return 0.5 + ((rx*7 + ry*13) % 6) * 0.2; }", 'caught'],
  ['粒が上下にばらけない',
   "      const y = Math.min(MAIN_GY - 1, oy + ry + Math.round(drift * 0.15 * dustLift(rx, ry)));",
   "      const y = oy + ry;", 'caught'],
  // ── メーターの見え方 ──
  ['満腹のあいだも目減りを描く（食べた直後から欠けて見える）',
   "    if((pet.hunger||0) >= HUNGER_MAX) return HUNGER_MAX;", "", 'caught'],
  ['きげんも上限で保たない',
   "    if((pet.mood||0) >= moodCap()) return pet.mood||0;", "", 'caught'],
  ['きげんを上限ではなく満点で判定する（汚れているとき保たれない）',
   "    if((pet.mood||0) >= moodCap()) return pet.mood||0;",
   "    if((pet.mood||0) >= MOOD_MAX) return pet.mood||0;", 'caught'],

  ['おもいでの日数を、数が後ろの並びに戻す',
   "      ctxR.fillText(petDay() + ' ' + T('mdays'), (W*S)/2, 44*S);",
   "      ctxR.fillText(T('mdays') + '  ' + petDay(), (W*S)/2, 44*S);", 'caught'],

  ['別れかたの2行目を描かない（お迎え・侵攻が言いさしで切れる）',
   "        e.split('\\n').forEach((line, i) => ctxR.fillText(line, (W*S)/2, (MEM_END_Y + i*MEM_END_LH)*S));",
   "        ctxR.fillText(e.split('\\n')[0], (W*S)/2, MEM_END_Y*S);", 'caught'],
  ['餓死と病死で ちがう言葉に戻す',
   "endStarve:'ちからつきた', endSick:'ちからつきた',",
   "endStarve:'ちからつきた', endSick:'びょうきで たおれた',", 'caught'],
  ['別れかたの2行目がページ数に掛かる',
   "  const MEM_END_Y = 50, MEM_END_LH = 5;", "  const MEM_END_Y = 54, MEM_END_LH = 5;", 'caught'],

  ['育成画面を見ていなくても演出が進む（裏で終わって おもいでだけ開く）',
   "    if(scene !== 'main' || miniFrame || manualFrame) return;", "", 'caught'],
  ['門番を時間の進行より手前に置く（画面しだいで時間が止まる）',
   "    advancePet();   // リアルタイム進行（1分単位で処理）",
   "    if(scene !== 'main') return;\n    advancePet();", 'caught'],

  // ── 演出中の操作 ──
  ['演出中でも MENU が開く', "getElementById('mmenu'),()=>{ if(cutscenePlaying()) return; playClick();",
   "getElementById('mmenu'),()=>{ playClick();", 'caught'],
  ['演出中でも 十字が効く', "      if(cutscenePlaying()) return;\n      playClick(900); dpadAnim(el);",
   "      playClick(900); dpadAnim(el);", 'caught'],
  ['おばけを見たあとも操作できないままにする',
   "        || (pet.dead && !pet.memShown)    // 魂が抜けていくあいだ（見たあとの漂う姿は操作できる）",
   "        || pet.dead", 'caught'],

  ['家出の「・・・」をキャラの真上に戻す（退屈のときと位置が食い違う）',
   "      if(ufoT % (RUN_ON + RUN_OFF) < RUN_ON) stampEmo(ctxM, ICO_DOTS, x0, y, cw, NK);",
   "      if(ufoT % (RUN_ON + RUN_OFF) < RUN_ON) stamp(ctxM, ICO_DOTS, x0 + 2, y - 3, NK);", 'caught'],
  ['育成画面のマークだけ別の置き方にする',
   "    function emo(spr){ stampEmo(ctxM, spr, charX, charY + yOff - airOff, gw, NK); }",
   "    function emo(spr){ stamp(ctxM, spr, charX, charY - 3, NK); }", 'caught'],

  ['おもいでが夜に暗くなる（読みものの画面なのに空の色を使う）',
   "    const BG = OFF, DM = DIM, NK = ON;",
   "    const col = getColors(), BG = col.bg, DM = col.dim, NK = col.on;", 'caught'],

  // ── 家出エンディング ──
  ['家出で「・・・」の回数を変える', "  const RUN_ON = 9, RUN_OFF = 7, RUN_TIMES = 3;",
   "  const RUN_ON = 9, RUN_OFF = 7, RUN_TIMES = 5;", 'caught'],
  ['画面の外へ出きる前に終わる（歩いている途中でおもいでが開く）',
   "  function runawayLen(cw){ return RUN_STILL + Math.ceil((centerX(cw) + cw) / RUN_SPEED) + RUN_AFTER; }",
   "  function runawayLen(cw){ return RUN_STILL + Math.ceil(centerX(cw) / RUN_SPEED / 2) + RUN_AFTER; }", 'caught'],
  ['出ていったあとの間を無くす', "  const RUN_AFTER = 14;", "  const RUN_AFTER = 0;", 'caught'],

  // ── おもいでの姿 ──
  ['おもいでの1ページ目に姿を出さない',
   "      if(body) stamp(ctxR, body, Math.round((W - body[0].length)/2), MEM_CHAR_BOT - body.length, NK);",
   "", 'caught'],
  ['姿を上ぞろえで置く（背の高さで下の名前との間隔が変わる）',
   "      if(body) stamp(ctxR, body, Math.round((W - body[0].length)/2), MEM_CHAR_BOT - body.length, NK);",
   "      if(body) stamp(ctxR, body, Math.round((W - body[0].length)/2), 16, NK);", 'caught'],
  ['姿の足元を下げすぎて名前に掛ける',
   "  const MEM_CHAR_BOT = 28;", "  const MEM_CHAR_BOT = 33;", 'caught'],

  // ── 文字の読みやすさ ──
  ['おもいでの見出しを薄い色に戻す（読めない）',
   "      ctxR.font = uiFont(6); ctxR.fillStyle = NK; ctxR.textAlign = 'center';\n      ctxR.fillText(T('mgave'), (W*S)/2, 17*S);",
   "      ctxR.font = uiFont(6); ctxR.fillStyle = DM; ctxR.textAlign = 'center';\n      ctxR.fillText(T('mgave'), (W*S)/2, 17*S);", 'caught'],
  ['日記のページ数を薄い色に戻す',
   "      ctxT.font = uiFont(6); ctxT.fillStyle = ON;\n      ctxT.fillText((diaryPage + 1)",
   "      ctxT.font = uiFont(6); ctxT.fillStyle = DIM;\n      ctxT.fillText((diaryPage + 1)", 'caught'],
  ['「????」の点滅の片側を薄い色に戻す（半分の時間読めない）',
   "    ctxM.fillStyle=(fM%10<5) ? NK : BG;   // 薄色だと読めないので、濃↔消で点滅させる",
   "    ctxM.fillStyle=(fM%10<5) ? NK : DM;", 'caught'],

  ['タイトルの選択肢を薄い色で描く（読みにくい）',
   "          ctxO.fillStyle = on ? ON : OFF;\n          ctxO.fillText(o.t, cx, y);",
   "          ctxO.fillStyle = on ? DIM : OFF;\n          ctxO.fillText(o.t, cx, y);", 'caught'],
  ['押せないお世話の名前を薄くする（どの項目にいるか読めない）',
   "        ctxN.fillStyle = ON;\n        ctxN.fillText(T(CARE_ORDER[menuSel].toLowerCase()), (W*S)/2, 36*S);",
   "        ctxN.fillStyle = careDisabled(CARE_ORDER[menuSel]) ? DIM : ON;\n        ctxN.fillText(T(CARE_ORDER[menuSel].toLowerCase()), (W*S)/2, 36*S);", 'caught'],

  // ── ベストスコアの表示 ──
  ['選択画面に点数を出さない',
   "      ctxN.fillText('BEST ' + bestText(playSel), (W*S)/2, 60*S);", "", 'caught'],
  ['選択画面が いつも1つ目のゲームの点数を出す（カーソルに追随しない）',
   "      ctxN.fillText('BEST ' + bestText(playSel), (W*S)/2, 60*S);",
   "      ctxN.fillText('BEST ' + bestText(0), (W*S)/2, 60*S);", 'caught'],
  ['未プレイでも 0点 と出す（遊んで0点だったのと区別がつかない）',
   "    if(!(Number.isFinite(p[k]) && p[k] > 0)) return '---';\n    return String(Math.max(0, Math.round(b[k] || 0)));",
   "    return String(Math.max(0, Math.round(b[k] || 0)));", 'caught'],
  ['おもいでに点数を並べない',
   "      PLAY_ITEMS.forEach((label,i)=> memGameRow(label, bestText(i), playText(i), 32 + i*8));", "", 'caught'],
  ['おもいでのページ数を増やし忘れる（さいごの すがたへ行けなくなる）',
   "  const MEM_PAGES = 4;", "  const MEM_PAGES = 3;", 'caught'],

  // ── ボタンの字の位置 ──
  ['A・B の字がボタンの中心からずれる（位置合わせを外す）',
   "    transform: translate(0.061em, 0.0625em);", "", 'caught'],
  ['MENU の字がずれる（字間ぶんの補正まで戻す）',
   "    transform: translate(0.103em, 0.0625em);   /* 横は 字間が最後の字のうしろにも入るぶんを含む */",
   "    transform: translate(0.061em, 0.0625em);", 'caught'],

  // ── ミニゲームの逃げ道 ──
  ['ミニゲームが立ち上がらなくても閉じない（画面を覆ったまま固まる）',
   "    miniGuard = setTimeout(()=>{ if(miniFrame === f && !miniAlive(f)) closeMiniGame(true); }, MINI_GUARD_MS);",
   "", 'caught'],
  ['閉じるときに見張りを解除しない（次に開いたゲームを巻き添えにする）',
   "    if(miniGuard){ clearTimeout(miniGuard); miniGuard = 0; }", "", 'caught'],
  ['生死を canvas の有無だけで見る（中が落ちた場合を取り逃す）',
   "      const px = cv.getContext('2d').getImageData(0, 0, 2, 2).data;", "      return true;", 'caught'],

  // ── 端末の時計 ──
  ['時計を戻されても立て直さない（実時間が追いつくまで進行が止まる）',
   "    if(elapsed < 0){ rewindClock(-elapsed); return; }   // 時計が戻された", "", 'caught'],
  ['時計を戻したとき、lastTick だけ直して他の時刻を置き去りにする',
   "    PET_TIMES.forEach(k => { if(pet[k]) pet[k] = Math.max(0, pet[k] - back); });",
   "    pet.lastTick = Date.now();", 'caught'],
  ['DAY の下限を外す（たんじょうが未来だと DAY:-2 と出る）',
   "    return Math.max(1, Math.min(99, days + 1));   // 誕生日=DAY01、次の0:00でDAY02",
   "    return Math.min(99, days + 1);", 'caught'],

  // ── 説明書 ──
  ['タイプの呼び名を変える（説明書だけ古いまま残る）',
   "      gray:'グレイ', martian:'マーシャン', invader:'ノーマル',",
   "      gray:'グレイ', martian:'カセイジン', invader:'ノーマル',", 'caught'],
  ['さいごの分岐を2つに減らす（説明書の「9とおり」と食い違う）',
   "    return n === '1' ? T('plump') : n === '2' ? T('sleek') : n === '3' ? T('prickly') : '';",
   "    return n === '1' ? T('plump') : n === '2' ? T('sleek') : n === '3' ? T('sleek') : '';", 'caught'],

  // ── ストーリー ──
  ['英語だけ段落を足す（日本語と切れ目がずれる）',
   "    'By this little invader.',", "    '',\n    'By this little invader.',", 'caught'],
  ['日本語に漢字が混ざる（この機械は漢字を出さない）',
   "    'この、ちいさな インベーダーに。',", "    'この、小さな インベーダーに。',", 'caught'],
  ['書き出しから雨が消える（到着の演出と辻褄が合わなくなる）',
   "    'その ひは、あさから あめだった。',", "    'その ひは、あさから かぜが つよかった。',", 'caught'],

  // ── 到着の演出 ──
  ['雨が降らない（うすぐらいだけの画面から始まる）',
   "  const ARR_RAIN_N = 14;", "  const ARR_RAIN_N = 0;", 'caught'],
  ['雨がやまない（赤ちゃんが降りてくる裏で降り続ける）',
   "    if(ph > ARR_RAIN_PH) return 0;", "    if(ph > ARR_RAIN_PH) return ARR_RAIN_N;", 'caught'],
  ['ビームより先に雨がやむ（稲光と結びつかない）',
   "  const ARR_RAIN_PH = 2;", "  const ARR_RAIN_PH = 1;", 'caught'],
  ['雨が1コマで消える（止んだというより描き落としに見える）',
   "  const ARR_RAIN_STOP = 4;", "  const ARR_RAIN_STOP = 1;", 'caught'],
  ['雨を見せる間が無い（始まってすぐビームが来る）',
   "  const ARR_PH = [18, 16, 10, 26, 10, 18, 6];",
   "  const ARR_PH = [2, 16, 10, 26, 10, 18, 6];", 'caught'],
  ['ビームが最初から地面まで届いている（伸びてこない）',
   "    if(y > Math.round(ARR_BEAM_TOP + (botY-ARR_BEAM_TOP)*progress)) return -1;", "", 'caught'],
  ['ビームが上に向かってすぼまらず、逆さの円錐になる',
   "    return Math.round(((y-ARR_APEX)/(botY-ARR_APEX)) * ARR_MAX_HALF);",
   "    return Math.round(((botY-y)/(botY-ARR_APEX)) * ARR_MAX_HALF);", 'caught'],
  ['雨をビームより先に描く（光の中の粒が上書きされて消える）',
   "      drawArrivalBeam(beamP, BG);\n      updateArrivalRain(BG, DM, beamP, shown);",
   "      updateArrivalRain(BG, DM, beamP, shown);\n      drawArrivalBeam(beamP, BG);", 'caught'],
  ['雨の粒を暗い色で描く（暗転した画面に沈んで見えない）',
   "        dot(ctxM, d.x, y, (half >= 0 && Math.abs(d.x-ARR_CX) <= half) ? DM : BG);",
   "        dot(ctxM, d.x, y, DM);", 'caught'],
  ['到着の演出が長すぎる（名前をつけるまで待たされる）',
   "  const ARR_PH = [18, 16, 10, 26, 10, 18, 6];",
   "  const ARR_PH = [80, 16, 10, 26, 10, 18, 6];", 'caught'],
  ['雨の粒が画面の外から降ってくる',
   "      y: ARR_BEAM_TOP + Math.random()*(MAIN_GY-1-ARR_BEAM_TOP),",
   "      y: ARR_BEAM_TOP - Math.random()*20,", 'caught'],

  ['昇りはじめと同時に体が散る（魂がまだ中にいるのに崩れる）',
   "      const dp = (p <= s0) ? 0 : (p - s0) / (1 - s0);", "      const dp = p;", 'caught'],
  ['散りはじめが早すぎる（離れる前から崩れる）',
   "    return Math.max(0, Math.min(0.85, (MAIN_GY - bodyTop) / span));",
   "    return 0.05;", 'caught'],
  ['散りはじめが遅すぎて、散る間が無い',
   "    return Math.max(0, Math.min(0.85, (MAIN_GY - bodyTop) / span));",
   "    return 0.99;", 'caught'],
  ['チリが地面より下へ飛ぶ',
   "      const y = Math.min(MAIN_GY - 1, oy + ry + Math.round(drift * 0.15 * dustLift(rx, ry)));",
   "      const y = oy + ry + Math.round(drift * 0.15 * dustLift(rx, ry));", 'caught'],
  ['魂が左右に揺れない',
   "  const GHOST_SWAY_X = 2;", "  const GHOST_SWAY_X = 0;", 'caught'],
  ['魂が揺れすぎる',
   "  const GHOST_SWAY_X = 2;", "  const GHOST_SWAY_X = 14;", 'caught'],
  ['魂の足元が地面より下から出る',
   "        const from  = MAIN_GY - GHOST_SPR.length;",
   "        const from  = by;", 'caught'],
  ['体を薄れさせる仕組みが効かない（最後まで全部残る）',
   "  function fadeKeeps(rx, ry, keep){ return DITHER4[ry & 3][rx & 3] / 16 < keep; }",
   "  function fadeKeeps(rx, ry, keep){ return true; }", 'caught'],
  ['おもいでを見たあとも昇り続ける（画面から消えたままになる）',
   "    if(pet.memShown){", "    if(false){", 'caught'],
  ['おもいでを何度でも開いてしまう',
   "  function endedShowMemory(){ if(!pet.memShown){ pet.memShown = true; savePet(); memOpen('main'); } }",
   "  function endedShowMemory(){ pet.memShown = true; savePet(); memOpen('main'); }", 'caught'],
  ['おもいでがメニューに並ばなくなる',
   "const head = (pet.gone || pet.dead) ? [['MEMORY','memory']] : [];", 'const head = [];', 'caught'],
  ['おもいでが育成中にも並んでしまう',
   "const head = (pet.gone || pet.dead) ? [['MEMORY','memory']] : [];", "const head = [['MEMORY','memory']];", 'caught'],
  ['通算カウンタを数えない',
   "        pet.total.feed++;                                           // 通算（おもいで用）", '', 'caught'],
  ['日記に段階を焼き付けない（読み返すと今の字になる）',
   "lv: diaryLevel(), wr: Math.round(writeRatio() * 100) / 100 };",
   "wr: Math.round(writeRatio() * 100) / 100 };", 'caught'],
  ['うまれたての日記だけ、また別扱いされる（初日の一言が読めなくなる）',
   "    drawDiaryText(e);",
   "    if(e && e.lv === LV_NEW){} else drawDiaryText(e);", 'caught'],
  ['初日から満量で書く（だんだん長くなる感じが消える）',
   "const cap = Math.min(4, Math.max(1, petDay()));", "const cap = 4;", 'caught'],
  ['来たばかりの子の書く量を絞らない',
   "    const cap = Math.min(4, Math.max(1, petDay()));", "    const cap = 4;", 'caught'],
  ['書く量が日を追って増えない（ずっと1話題）',
   "    const cap = Math.min(4, Math.max(1, petDay()));", "    const cap = 1;", 'caught'],
  ['幼いうちにも結びの言葉を書かせる',
   "      close:  diaryLevel() <= LV_BABY ? '' : voice(),",
   "      close:  voice(),", 'caught'],
  ['飛んでくる薬が1色になる（押したアイコンと結びつかない）',
   "    [0,0,0,2,1,1,1,1,2],", "    [0,0,0,2,2,2,2,2,2],", 'caught'],
  ['飛んでくる薬に薄色を渡さない（絵は2色でも全部濃色で出る）',
   "stamp(ctxM, MED_PILL, pos.x, pos.y, NK, DM);",
   "stamp(ctxM, MED_PILL, pos.x, pos.y, NK);", 'caught'],
  ['ゲームのアイコンの十字キーが潰れる（何のアイコンか読めない）',
   "##...#########", "#############.", 'caught'],
  ['ゲームのアイコンの肩が左右でずれる（傾いて見える）',
   "...###..###...", "...###...###..", 'caught'],
  ['ゲームのアイコンのグリップが1つに繋がる（割れていない四角に見える）',
   ".##........##.", ".############.", 'caught'],
  ['ゲームのアイコンのグリップが3つに割れる（脚が生えて見える）',
   ".##........##.", ".##.#....#.##.", 'caught'],
  ['本文の文字の大きさを言語で変えない（英語が長すぎて はみ出す）',
   "    const fs = (lang === 'ja') ? 10 : 6;",
   "    const fs = 10;", 'caught'],
  ['本文の書体を言語で切り替えない（日本語が四角い字体に落ちる）',
   "    ctxT.font = (lang==='ja') ? (fs+'px '+JP_FONT) : fs+'px \"Press Start 2P\"';",
   "    ctxT.font = fs+'px \"Press Start 2P\"';", 'caught'],
  ['初回起動の言語を英語に戻す',
   "let lang = 'ja';\n  try{ if(localStorage.getItem('myvader_lang') === 'en') lang = 'en'; }catch(e){}",
   "let lang = 'en';\n  try{ if(localStorage.getItem('myvader_lang') === 'ja') lang = 'ja'; }catch(e){}", 'caught'],
  ['体型の呼び名が末尾と対応しなくなる',
   "return n === '1' ? T('plump') : n === '2' ? T('sleek') : n === '3' ? T('prickly') : '';",
   "return n === '1' ? T('sleek') : n === '2' ? T('plump') : n === '3' ? T('prickly') : '';", 'caught'],
  ['別れの形を見分けなくなる',
   "if(pet.goneBy === 'invade') return T('endInvade');", '', 'caught'],
  // 各分岐が個別に就寝判定を持つので、冒頭のガードだけ外しても挙動は変わらない
  ['doCare 冒頭の無効ガードだけ外す',
   '    if(careDisabled(act)) return;\n', '    \n', 'equivalent'],
  ['ページ割りを均さず、上限まで詰めこむ（最後のページだけ すかすかになる）',
   "const pages = layout(lo).length <= n ? layout(lo) : layout(avail);",
   "const pages = layout(avail);", 'caught'],
  ['段落のあいだの空きを詰める（かなの本文が壁のように見える）',
   "const STORY_PARA = 8;", "const STORY_PARA = 0;", 'caught'],
  ['日記の結びを、また「ぶじにおわった」に戻す',
   "{ ja:['ゆうひが しずむのを','ずっと みていた'], en:['I WATCHED THE SUN','GO DOWN'] },",
   "{ ja:['きょうも ぶじに','おわった'], en:['ANOTHER DAY','ENDED SAFELY'] },", 'live'],
  ['iOSの割り込み(interrupted)を見のがす（電話のあと ずっと無音になる）',
   "    if(ac.state === 'suspended'){ ac.resume().catch(()=>{}); return; }\n    // interrupted / closed。作り直す。ただし歯止めの内側では触らない\n    if(Date.now() - acBornAt < AC_RETRY) return;",
   "    if(ac.state === 'suspended'){ ac.resume().catch(()=>{}); return; }\n    return;\n    if(Date.now() - acBornAt < AC_RETRY) return;", 'caught'],
  ['作り直しても古い口を閉じない（iOSは同時に持てる数に限りがある）',
   "    try{ old.close(); }catch(e){}", "", 'caught'],
  ['割り込み中に口を作り続ける（歯止めを外す）',
   "    if(Date.now() - acBornAt < AC_RETRY) return;", "", 'caught'],
  ['SOUND=OFF でも口を開けてしまう',
   "    if(!soundOn) return;   // SOUND=OFFならミュート\n    ensureAudio();",
   "    ensureAudio();\n    if(!soundOn) return;", 'caught'],
  //  版の番号はコミットのたびに上がるので、番号そのものは書かない。
  //  頭に1字足して sw.js とずらす
  ['画面に出す版を、sw.js とずらす',
   "const APP_VERSION = '", "const APP_VERSION = 'x", 'caught'],
  ['著作権を © で書く（Press Start 2P に無く、1文字だけ字体が浮く）',
   "const APP_COPY = '(C) 2026 Studio M.D.Q.';", "const APP_COPY = '\u00a9 2026 Studio M.D.Q.';", 'caught'],
  ['著作権の名義を落とす',
   "const APP_COPY = '(C) 2026 Studio M.D.Q.';", "const APP_COPY = '(C) 2026';", 'caught'],
  ['SETTINGS の行間をもとの8ドットに戻す（いちばん下が画面から出る）',
   "      const ITEM_H = 7;", "      const ITEM_H = 8;", 'caught'],
  ['バージョンの項目を消す',
   "const SETTINGS_KEYS = ['language','weather','sound','bodycolor','version','reset'];",
   "const SETTINGS_KEYS = ['language','weather','sound','bodycolor','reset'];", 'caught'],
  ['一覧の行にも版の番号を出す（点線と数字でその一行だけ賑やかになる）',
   "                  : key==='debug'     ? (debugMode?T('on'):T('off'))",
   "                  : key==='debug'     ? (debugMode?T('on'):T('off'))\n                  : key==='version'   ? APP_VERSION", 'caught'],
  ['バージョンの画面から版を落とす',
   "        ctxN.fillText('VER ' + APP_VERSION,(W*S)/2, 37*S);", "", 'caught'],
  ['列の仕切りを消す',
   "      ctxN.fillRect(26*S + S/4, Y0*S, S/2, rows*HL_H*S);", "", 'caught'],
  ['列の仕切りを、右の列の網掛けに重ねる',
   "      ctxN.fillRect(26*S + S/4, Y0*S, S/2, rows*HL_H*S);",
   "      ctxN.fillRect(27*S + S/4, Y0*S, S/2, rows*HL_H*S);", 'caught'],
  ['列の仕切りを1ドットの太さに戻す（項目の字と同じ太さで、区切りに見えない）',
   "      ctxN.fillRect(26*S + S/4, Y0*S, S/2, rows*HL_H*S);",
   "      ctxN.fillRect(26*S, Y0*S, S, rows*HL_H*S);", 'caught'],
  ['列の仕切りを、ドットの中央からずらす',
   "      ctxN.fillRect(26*S + S/4, Y0*S, S/2, rows*HL_H*S);",
   "      ctxN.fillRect(26*S + S/2, Y0*S, S/2, rows*HL_H*S);", 'caught'],
  ['4行のときも行間を7に戻す（仕切りの下端が画面から出る）',
   "      const HL_H = (rows >= 4) ? 6 : 7;", "      const HL_H = 7;", 'caught'],
  ['くすりの中身の色を輪郭と同じにする（ただの塊に見える）',
   ".......#+++#.\n......#+++++#\n.....#++++++#\n....##++++++#\n...#.##++++#.\n..#...##++#..",
   ".......#####.\n......#######\n.....########\n....#########\n...#.#######.\n..#...#####..", 'caught'],
  ['くすりの輪郭に穴をあける（空いている側が外へつながる）',
   ".#......#....", ".#...........", 'caught'],
  ['くすりを片側だけの塗りつぶしにする（空いている側が無くなる）',
   ".#.....###...\n.#......#....\n.#.....#.....\n..#...#......\n...###.......",
   ".#####+##...\n.#+++++#.....\n.#+++++#.....\n..#+++#......\n...###.......", 'caught'],
  ['押せないアイコンでも、ふだんの音と断りの音が二重に鳴る',
   "    playClick(onDisabledCare() ? 300 : 900);",
   "    playClick(900); setTimeout(()=>playClick(300), 60);", 'caught'],
  ['押せないアイコンでも、ふだんの音だけ鳴る（断られたと分からない）',
   "    playClick(onDisabledCare() ? 300 : 900);", "    playClick(900);", 'caught'],
  ['押せるアイコンまで断りの音になる',
   "    playClick(onDisabledCare() ? 300 : 900);", "    playClick(300);", 'caught'],
  ['サブ画面でもアイコンの状態を見てしまう',
   "    return !inSettings && !inStatus && !inFeed && !inPlay\n        && menuSel < 6 && careDisabled(CARE_ORDER[menuSel]);",
   "    return menuSel < 6 && careDisabled(CARE_ORDER[menuSel]);", 'caught'],
  ['日記のマークが、また未読のときだけ出るようになる',
   "    if(diaryUnlocked()) list.push('diary');", "    if(diaryUnread > 0) list.push('diary');", 'caught'],
  ['ステータスのマークが出ない',
   "    if(!pet.gone && !pet.dead) list.push('status');", "", 'caught'],
  ['別れたあともステータスのマークが残る',
   "    if(!pet.gone && !pet.dead) list.push('status');", "    list.push('status');", 'caught'],
  ['ステータスの知らせが 点きっぱなしになる',
   "  function statusAlert(){ return healthState() !== 'good'; }",
   "  function statusAlert(){ return true; }", 'caught'],
  ['ステータスの知らせが まったく点かない',
   "  function statusAlert(){ return healthState() !== 'good'; }",
   "  function statusAlert(){ return false; }", 'caught'],
  ['知らせを けんこうの文字と別に決める（ふつうでも点く）',
   "  function statusAlert(){ return healthState() !== 'good'; }",
   "  function statusAlert(){ return healthState() !== 'dead'; }", 'caught'],
  ['マークが DAY の表示に重なる',
   "    const right = 130;", "    const right = 152;", 'caught'],
  ['マークが 名前に重なるほど左へ寄る',
   "    const right = 130;", "    const right = 96;", 'caught'],
  ['マークどうしが重なる',
   "  const HEAD_ICON_W = 12, HEAD_ICON_H = 12, HEAD_ICON_GAP = 4;",
   "  const HEAD_ICON_W = 12, HEAD_ICON_H = 12, HEAD_ICON_GAP = -4;", 'caught'],
  ['文字とマークの中心がずれる',
   "  const HEAD_IY = 10;", "  const HEAD_IY = 4;", 'caught'],
  ['マークが ヘッダーの帯からはみ出す',
   "  const HEAD_ICON_W = 12, HEAD_ICON_H = 12, HEAD_ICON_GAP = 4;",
   "  const HEAD_ICON_W = 12, HEAD_ICON_H = 24, HEAD_ICON_GAP = 4;", 'caught'],
  ['3つのマークの大きさがそろわなくなる',
   "    [0,0,0,0,0,1,1,0,0,0,0,0],\n    [0,0,0,0,0,1,1,0,0,0,0,0],\n    [0,0,1,1,1,1,1,1,1,1,0,0],",
   "    [0,0,0,0,0,1,1,0,0,0,0],\n    [0,0,0,0,0,1,1,0,0,0,0],\n    [0,0,1,1,1,1,1,1,1,1],", 'caught'],
  ['ヘッダーのマークの左右が入れかわる',
   "    if(diaryUnlocked()) list.push('diary');                 // 1件も書かれていないうちは、選ばせない（開いても空）\n    if(!pet.gone && !pet.dead) list.push('status');",
   "    if(!pet.gone && !pet.dead) list.push('status');\n    if(diaryUnlocked()) list.push('diary');                 // 1件も書かれていないうちは、選ばせない（開いても空）", 'caught'],
  ['日記が1件も無くても、日記のマークが選べてしまう',
   "    if(diaryUnlocked()) list.push('diary');", "    list.push('diary');", 'caught'],
  ['えらんでいるマークを薄色のまま描く（薄色の枠に溶けて消える）',
   "(sel || blink) ? NK : DM", "blink ? NK : DM", 'caught'],
  ['ステータスの棒が ぜんぶ同じ長さになる（グラフに見えない）',
   "    [1,1,1,1,1,1,1,1,0,0,0,0],\n    [1,1,1,1,1,1,1,1,0,0,0,0],\n    [1,1,1,1,1,1,1,1,0,0,0,0],",
   "    [1,1,1,1,1,0,0,0,0,0,0,0],\n    [1,1,1,1,1,0,0,0,0,0,0,0],\n    [1,1,1,1,1,0,0,0,0,0,0,0],", 'caught'],
  ['ステータスの棒が「長い・短い・長い」に戻る（E の字に見える）',
   "    [1,1,1,1,1,0,0,0,0,0,0,0],\n    [1,1,1,1,1,0,0,0,0,0,0,0],\n    [1,1,1,1,1,0,0,0,0,0,0,0],",
   "    [1,1,1,1,1,1,1,1,1,1,1,1],\n    [1,1,1,1,1,1,1,1,1,1,1,1],\n    [1,1,1,1,1,1,1,1,1,1,1,1],", 'caught'],
  ['ステータスの棒から左の軸が消える',
   "    [1,0,0,0,0,0,0,0,0,0,0,0],\n    [1,1,1,1,1,0,0,0,0,0,0,0],", "    [0,0,0,0,0,0,0,0,0,0,0,0],\n    [0,1,1,1,1,0,0,0,0,0,0,0],", 'caught'],
  ['ステータスの棒のあいだの空きが無くなる（ひとかたまりに見える）',
   "    [1,0,0,0,0,0,0,0,0,0,0,0],\n    [1,1,1,1,1,1,1,1,0,0,0,0],", "    [1,1,1,1,1,1,0,0,0,0,0,0],\n    [1,1,1,1,1,1,1,1,0,0,0,0],", 'caught'],
  ['日記の中の横線が減る（ただの箱に見える）',
   "    [1,1,0,1,1,1,1,1,1,1,0,1],\n    [1,1,0,0,0,0,0,0,0,0,0,1],\n    [1,1,0,0,0,0,0,0,0,0,0,1],\n    [1,1,0,1,1,1,1,1,1,1,0,1],",
   "    [1,1,0,0,0,0,0,0,0,0,0,1],\n    [1,1,0,0,0,0,0,0,0,0,0,1],\n    [1,1,0,0,0,0,0,0,0,0,0,1],\n    [1,1,0,0,0,0,0,0,0,0,0,1],", 'caught'],
  ['せっていのマークが出ない',
   "    list.push('settings');                                  // せっていは いつでも開ける", "", 'caught'],
  ['せっていのマークが 知らせを持ってしまう（点滅する）',
   "    return k === 'status' ? statusAlert()\n         : k === 'diary'  ? diaryUnread > 0\n         : false;",
   "    return k === 'status' ? statusAlert()\n         : k === 'diary'  ? diaryUnread > 0\n         : true;", 'caught'],
  ['せっていのマークだけ いつも濃い色になる（ほかと ちぐはぐに見える）',
   "(sel || blink) ? NK : DM", "(sel || blink || k === 'settings') ? NK : DM", 'caught'],
  ['上を押すと、点滅を無視していちばん左が選ばれる',
   "        if(el.classList.contains('up')   && !headSel) headSel = headDefault();",
   "        if(el.classList.contains('up')   && !headSel) headSel = list[0];", 'caught'],
  ['両方点滅しているとき、日記が先に選ばれる',
   "    for(const k of ['status', 'diary']) if(list.includes(k) && headAlert(k)) return k;",
   "    for(const k of ['diary', 'status']) if(list.includes(k) && headAlert(k)) return k;", 'caught'],
  ['どれも点いていないとき、せっていではなく いちばん左が選ばれる',
   "    return list.includes('settings') ? 'settings' : list[0];", "    return list[0];", 'caught'],
  ['命名前でも ヘッダーのマークが出る（???? が選べなくなる）',
   "    if(!pet.name) return list;                              // 命名前は ????（名前）を選ばせる", "", 'caught'],
  ['マークと DAY のあいだの仕切りを消す',
   "      ctxM.fillRect(last + HEAD_ICON_GAP/2, HEAD_IY, S/2, HEAD_ICON_H);", "", 'caught'],
  ['仕切りを マークと同じ太さにする（もう1つマークがあるように見える）',
   "      ctxM.fillRect(last + HEAD_ICON_GAP/2, HEAD_IY, S/2, HEAD_ICON_H);",
   "      ctxM.fillRect(last + HEAD_ICON_GAP/2, HEAD_IY, S, HEAD_ICON_H);", 'caught'],
  ['マークが1つも無くても 仕切りを引く',
   "    if(list.length){\n      const last = headIconX(list.length-1, list.length) + HEAD_ICON_W;",
   "    {\n      const last = headIconX(Math.max(0,list.length-1), Math.max(1,list.length)) + HEAD_ICON_W;", 'caught'],
  ['十字が 演出中でも効いてしまう',
   "      if(openingLocked()) return;\n      playClick(900); dpadAnim(el);",
   "      if(manualFrame) return;\n      playClick(900); dpadAnim(el);", 'caught'],
  ['MENU が 演出中でも音を出す',
   "    if(openingLocked()) return;\n    playClick(); btnAnim(document.getElementById('omenu'),1,0.93);",
   "    playClick(); btnAnim(document.getElementById('omenu'),1,0.93);", 'caught'],
  ['START でも ことばをえらばせない（いきなり始まる）',
   "      openStep = 1; langSel = (lang === 'en') ? 1 : 0; return;",
   "      if(!pet.name && !pet.birth) startArrival(); openStep = 0; showView('main'); return;", 'caught'],
  ['ことばを決めても 設定に反映しない',
   "    setLang(LANG_OPTS[langSel].k);\n    if(!pet.name && !pet.birth) startArrival();",
   "    if(!pet.name && !pet.birth) startArrival();", 'caught'],
  ['MANUAL でも ことばをえらばされる',
   "      if(OPEN_OPTS[openSel] === 'MANUAL'){\n        openManual();                             // 閉じると この選択肢に戻ってくる\n        return;\n      }",
   "      if(OPEN_OPTS[openSel] === 'MANUAL'){\n        openStep = 2; return;\n      }", 'caught'],
  ['ことばえらびが いまの設定を見ない（毎回いちばん上に戻る）',
   "openStep = 1; langSel = (lang === 'en') ? 1 : 0; return;", "openStep = 1; langSel = 0; return;", 'caught'],
  ['ことばの名前を どちらも英語で書く（読めないほうを選ばされる）',
   "{ k:'ja', t:'にほんご', jp:true }", "{ k:'ja', t:'JAPANESE', jp:false }", 'caught'],
  ['MANUAL をえらんでも ゲームが始まってしまう',
   "        openManual();                             // 閉じると この選択肢に戻ってくる\n        return;",
   "        openManual();", 'caught'],
  ['タイトルの選択肢が日本語になる（言語を選ぶ前の画面なのに）',
   "  const OPEN_OPTS = ['MANUAL', 'START'];", "  const OPEN_OPTS = ['せつめいしょ', 'はじめる'];", 'caught'],
  ['説明書と はじめるの上下が入れかわる',
   "  const OPEN_OPTS = ['MANUAL', 'START'];", "  const OPEN_OPTS = ['START', 'MANUAL'];", 'caught'],
  ['はじめから選択肢が出ている',
   "  let openStep = 0, openSel = 0, langSel = 0;", "  let openStep = 1, openSel = 0, langSel = 0;", 'caught'],
  ['到着のあと、命名画面へ送らない',
   "    if(nameOpenT < 0) nameOpenT = ARR_TO_NAME;", "", 'caught'],
  ['一拍のあいだ、ふつうの育成画面に戻してしまう（就寝時間帯だと寝姿が見える）',
   "    arriveT = ARR_TOTAL - 1;\n    if(nameOpenT < 0) nameOpenT = ARR_TO_NAME;",
   "    arriveT = -1;\n    if(nameOpenT < 0) nameOpenT = ARR_TO_NAME;", 'caught'],
  ['名前がついていても 命名画面へ送ってしまう',
   "    if(pet.name){ arriveT = -1; return; }", "", 'caught'],
  ['到着のあと 間を置かずに命名画面が開く（着地を見とどけられない）',
   "  const ARR_TO_NAME = 9;", "  const ARR_TO_NAME = 0;", 'caught'],
  ['待っているあいだに ボタンが効いてしまう',
   "        || nameOpenT >= 0;                // 到着のあと、命名画面が開くまでの一拍",
   "        || false;", 'caught'],
  ['えらんでいる行が点滅しない（どれを選んでいるか動きで分からない）',
   "          const on = (i !== sel) || blink;", "          const on = true;", 'caught'],
  ['えらんでいない行まで点滅する',
   "          const on = (i !== sel) || blink;", "          const on = blink;", 'caught'],
  ['点滅の片側を薄い色にする（半分の時間読めない）',
   "          ctxO.fillStyle = on ? ON : OFF;", "          ctxO.fillStyle = on ? ON : DIM;", 'caught'],
  ['選択肢のあいだが広がって、ばらばらに見える',
   "  const OPT_Y0 = 37, OPT_H = 6;", "  const OPT_Y0 = 37, OPT_H = 9;", 'caught'],
  ['選択肢のあいだが詰まりすぎて 字が重なる',
   "  const OPT_Y0 = 37, OPT_H = 6;", "  const OPT_Y0 = 37, OPT_H = 2;", 'caught'],
  ['選択中の印を ＞（文字）に戻す（字体が浮く）',
   "        if(isSel) selMark(ctxN, 2*S, cy, ON);\n        ctxN.fillText(T(key), 7*S, cy);",
   "        if(isSel) ctxN.fillText('>',2*S,cy);\n        ctxN.fillText(T(key), 7*S, cy);", 'caught'],
  ['タイトルの ▶ まで点滅する（字が消えると どこを選んでいるか分からない）',
   "          if(i === sel) selMark(ctxO, cx - w/2 - 9, y, ON);",
   "          if(i === sel && on) selMark(ctxO, cx - w/2 - 9, y, ON);", 'caught'],
  ['▶ が三角に見えない（同じ長さの棒が並ぶ）',
   "      const w = 2*i+1;                           // その段の縦の長さ（1が頂点、Lが底）",
   "      const w = L;", 'caught'],
  ['▶ が左向きになる',
   "      ctx.fillRect(x + (dir === 'left' ? i : t-1-i), y0 + (L-w)/2, 1, w);",
   "      ctx.fillRect(x + (dir === 'left' ? t-1-i : i), y0 + (L-w)/2, 1, w);", 'caught'],
  ['▶ が行の中心からずれる',
   "    const y0 = Math.round(cy - L/2);", "    const y0 = Math.round(cy);", 'caught'],
  ['英語の命名画面の見出しが、この子を指さない言い方に戻る',
   "      nameq:\"WHAT'S THEIR NAME?\", done:'DONE'", "      nameq:'NAME?', done:'DONE'", 'caught'],
  ['英語の見出しが 画面からはみ出す長さになる',
   "      nameq:\"WHAT'S THEIR NAME?\", done:'DONE'",
   "      nameq:\"WHAT SHOULD WE CALL THIS LITTLE ONE?\", done:'DONE'", 'caught'],
  ['命名画面の見出しが 画面からはみ出す長さになる',
   "      nameq:'このこの なまえは？', done:'けってい'", "      nameq:'このこのなまえをきめてあげてくださいなんでもいいですよ？', done:'けってい'", 'caught'],
  ['作れなかったときに いまの口を捨てる（二度と鳴らなくなる）',
   "    if(!fresh){ ac.resume().catch(()=>{}); return; }\n    const old = ac;\n    ac = fresh;",
   "    const old = ac;\n    ac = fresh;", 'caught'],
  ['作ろうとした時刻を、作れたときだけ記録する（作れないと毎回試す）',
   "    acBornAt = Date.now();                 // 「最後に作ろうとした時刻」。作れなくても歯止めに使う\n    try{ return new (window.AudioContext||window.webkitAudioContext)(); }\n    catch(e){ return null; }",
   "    try{ const c = new (window.AudioContext||window.webkitAudioContext)(); acBornAt = Date.now(); return c; }\n    catch(e){ return null; }", 'caught'],
  ['到着直後の おなかが また満タンになる',
   "    hunger:2.5, mood:2, health:'GOOD',", "    hunger:5, mood:2, health:'GOOD',", 'caught'],
  ['到着直後の きげんが また満タン近くになる',
   "    hunger:2.5, mood:2, health:'GOOD',", "    hunger:2.5, mood:4, health:'GOOD',", 'caught'],
  ['おなかが 0を通りこして負になる',
   "      while(pet.hungerAcc >= hm && pet.hunger > 0){ pet.hungerAcc -= hm; pet.hunger = Math.max(0, pet.hunger - 1); }",
   "      while(pet.hungerAcc >= hm && pet.hunger > 0){ pet.hungerAcc -= hm; pet.hunger--; }", 'caught'],
  ['ミニゲーム後の おなかが 0を通りこして負になる',
   "      if(pet.hungerAcc >= hm){ pet.hungerAcc -= hm; if(pet.hunger > 0) pet.hunger = Math.max(0, pet.hunger - 1); }",
   "      if(pet.hungerAcc >= hm){ pet.hungerAcc -= hm; if(pet.hunger > 0) pet.hunger--; }", 'caught'],
  ['にっきの ◀ が右向きになる（前へ戻る印に見えない）',
   "      if(diaryPage > 0)                 pageMark(ctxT, 'left',  4*S, 7*S + 4, ON);",
   "      if(diaryPage > 0)                 pageMark(ctxT, 'right', 4*S, 7*S + 4, ON);", 'caught'],
  ['ページ送りの印を また字（＜＞）で置く',
   "      if(diaryPage > 0)                 pageMark(ctxT, 'left',  4*S, 7*S + 4, ON);",
   "      if(diaryPage > 0)                 ctxT.fillText('<', 4*S, 7*S);", 'caught'],
  ['左向きの三角が 右向きになる',
   "      ctx.fillRect(x + (dir === 'left' ? i : t-1-i), y0 + (L-w)/2, 1, w);",
   "      ctx.fillRect(x + (t-1-i), y0 + (L-w)/2, 1, w);", 'caught'],
  ['説明書を閉じても、えらんだ ことばを引き継がない',
   "      const v = localStorage.getItem('myvader_lang') === 'en' ? 'en' : 'ja';\n      if(v !== lang) setLang(v);", "", 'caught'],
  ['瀕死でも 眠っていれば ふつうの寝姿に戻る（薄い色にならない）',
   "    if (isWeak()) {\n      // 瀕死：くうふくも びょうきも、",
   "    if (asleep) {\n      grid = sp.sleep; yOff = 0;\n    } else if (isWeak()) {\n      // 瀕死：くうふくも びょうきも、", 'caught'],
  ['瀕死でも 眠っていれば Zzz が出る（休んでいるように見える）',
   "    } else if (isWeak()) {\n      // 瀕死：速く点滅させて急を伝える。",
   "    } else if (asleep) {\n      if((fM%30)<24) emo(ICO_ZZZ);\n    } else if (isWeak()) {\n      // 瀕死：速く点滅させて急を伝える。", 'caught'],
  ['瀕死の姿が 濃い色のままになる',
   "      grid = sp.rest; yOff = 0; charCol = DM;", "      grid = sp.rest; yOff = 0;", 'caught'],
  ['瀕死でも 夜になると眠ってしまう',
   "    if(isWeak()) return false;\n    return isAsleep(new Date())", "    return isAsleep(new Date())", 'caught'],
  ['病気の瀕死が 無くなる（最後まで「びょうき」のまま）',
   "  function isWeakSick(){   return !pet.dead && pet.sickAcc   >= WEAK_SICK_MIN; }",
   "  function isWeakSick(){   return false; }", 'caught'],
  ['病気の瀕死が 早すぎる／遅すぎる',
   "  const WEAK_STARVE_MIN = 1080, WEAK_SICK_MIN = 1440;",
   "  const WEAK_STARVE_MIN = 1080, WEAK_SICK_MIN = 2100;", 'caught'],
  ['ふたつの ひんしが 同じ名前になる',
   "weakStarve:'ひんし（くうふく）', weakSick:'ひんし（びょうき）'",
   "weakStarve:'ひんし', weakSick:'ひんし'", 'caught'],
  ['瀕死のマークが どちらも ！ になる（病気か空腹か分からない）',
   "      if((fM%8)<5) emo(isWeakStarve() ? ICO_EXCL : ICO_SKULL);",
   "      if((fM%8)<5) emo(ICO_EXCL);", 'caught'],
  ['ひんし（びょうき）が ふだんの病気と同じ 汗になる',
   "      if((fM%8)<5) emo(isWeakStarve() ? ICO_EXCL : ICO_SKULL);",
   "      if((fM%8)<5) emo(isWeakStarve() ? ICO_EXCL : ICO_DROP);", 'caught'],
  ['ドクロの眼窩が 塞がる（顔に見えない）',
   "    [1,0,1,1,1,0,1],              //  眼窩は抜きで作る", "    [1,1,1,1,1,1,1],", 'caught'],
  ['ドクロの歯が 無くなる',
   "    [0,1,0,1,0,1,0],              //  歯3本。3本並べるには あご幅が5ドット要る",
   "    [0,1,1,1,1,1,0],", 'caught'],
  ['ドクロの歯が 2本に減る',
   "    [0,1,0,1,0,1,0],              //  歯3本。3本並べるには あご幅が5ドット要る",
   "    [0,1,0,0,0,1,0],", 'caught'],
  ['両方ひんしのとき、あとで死ぬ びょうきを出してしまう',
   "    if(isWeakStarve())        return 'weakStarve'; // 空腹18時間超。あと12時間で死\n    if(isWeakSick())          return 'weakSick';   // 病気24時間超。あと12時間で死",
   "    if(isWeakSick())          return 'weakSick';   // 病気24時間超。あと12時間で死\n    if(isWeakStarve())        return 'weakStarve'; // 空腹18時間超。あと12時間で死", 'caught'],
  ['寝ていると くすりを飲ませられない（起こすしか手が無くなる）',
   "      case 'MED':   return asleep && !needsMed();           // 健康な子に飲ませて嫌がられるのは有効な操作",
   "      case 'MED':   return asleep;", 'caught'],
  ['げんきな子にも 寝ているあいだ くすりを飲ませられる',
   "      case 'MED':   return asleep && !needsMed();           // 健康な子に飲ませて嫌がられるのは有効な操作",
   "      case 'MED':   return false;", 'caught'],
  ['寝ている子に くすりが効かない（押せるのに何も起きない）',
   "        if(asleep && !needsMed()) break;", "        if(asleep) break;", 'caught'],
  ['寝ている子も くすりを拒む（結局 起こすことになる）',
   "          if(!asleep && (pet.tantrumAt || rollTantrum('med'))){ setReaction('refuse'); }",
   "          if(pet.tantrumAt || rollTantrum('med')){ setReaction('refuse'); }", 'caught'],
  ['やまいの芽は くすりの対象から外れる',
   "  function needsMed(){ return pet.health === 'SICK' || !!pet.incubAt; }",
   "  function needsMed(){ return pet.health === 'SICK'; }", 'caught'],
];

const orig = fs.readFileSync(GAME, 'utf8');
let caught = 0, missed = [], unexpected = [], stale = [];
try {
  process.stdout.write('突然変異チェック（本体をわざと壊して、テストが落ちるかを見る）\n\n');
  for(const [name, from, to, expect] of MUTATIONS){
    // 本体を直すと from が古くなり、この変異は黙って死ぬ。見逃しと違って
    //  「✗」が出ないので気づきにくい。最後にまとめて出し、終了コードにも効かせる
    if(orig.split(from).length - 1 !== 1){
      stale.push(name);
      console.log(`  ？ 対象が1か所に定まらない  ${name}`); continue;
    }
    fs.writeFileSync(GAME, orig.replace(from, to));
    let died = false;
    try { execFileSync(process.execPath, [TEST], { stdio: 'pipe' }); }
    catch(e){ died = true; }
    const good = (expect === 'caught') ? died : !died;
    if(good && expect === 'caught') caught++;
    if(!good && expect === 'caught') missed.push(name);
    if(!good && expect === 'equivalent') unexpected.push(name);
    const mark = good ? (expect === 'caught' ? '✓ 検出' : '－ 挙動不変') : '✗ 見逃し';
    console.log(`  ${mark}  ${name}`);
  }
} finally {
  fs.writeFileSync(GAME, orig);
}
console.log('\n本体は元に戻した');
const total = MUTATIONS.filter(m => m[3] === 'caught').length;
console.log(`検出 ${caught} / ${total}`);
if(missed.length) console.log('見逃し: ' + missed.join(' , '));
if(stale.length){
  console.log(`\n空振り ${stale.length}件（本体が変わって from が古い。直すか消すこと）:`);
  for(const n of stale) console.log('  - ' + n);
}
process.exit((missed.length || stale.length) ? 1 : 0);
