// ══════════════════════════════════════════════════════════════
//  突然変異チェック。node tools/mutate.js で走る。
//
//  テストそのものが機能しているかを確かめる道具。本体をわざと壊して、
//  tools/test.js が落ちるかを見る。落ちなければ、その挙動は誰も見張っていない。
//
//  ここに並べてあるのは、実際にこのゲームで起きたバグの再現。
//  本体は毎回かならず元に戻す（途中で止めても復元されるよう finally で囲ってある）。
// ══════════════════════════════════════════════════════════════
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const GAME = path.join(__dirname, '..', 'invader_game.html');
// 二重に走らせない。この道具は本体を書き換えてから戻すので、
//  同時に2つ動くと 片方の書き戻しがもう片方の変異を「元の姿」として
//  固定してしまい、本体に壊れたコードが residue として残る（実際に起きた）。
const LOCK = path.join(__dirname, '.mutate.lock');
try{
  fs.writeFileSync(LOCK, String(process.pid), { flag: 'wx' });
}catch(e){
  console.error('別の突然変異チェックが動いています。終わってから実行してください。');
  console.error('（前回が異常終了した場合は ' + LOCK + ' を消してください）');
  process.exit(1);
}
const unlock = () => { try{ fs.unlinkSync(LOCK); }catch(e){} };
process.on('exit', unlock);
process.on('SIGINT', () => { unlock(); process.exit(130); });
const TEST = path.join(__dirname, 'test.js');

// [名前, 置換前, 置換後, 期待]  期待='caught' … 検出できるべき
//                               期待='equivalent' … 壊しても挙動が変わらない（検出できなくてよい）
const MUTATIONS = [
  ['なかよしの上限を連続日数と無関係にする',
   'const BOND_CAP = [1, 1, 2, 2, 3];', 'const BOND_CAP = [5, 5, 5, 5, 5];', 'caught'],
  ['ふれあいを種類ではなく回数で数える',
   'if(!k[kind]){ k[kind] = 1; pet.touchCount = (pet.touchCount||0) + 1; }',
   'pet.touchCount = (pet.touchCount||0) + 1;', 'caught'],
  ['治した病気も放置に数える',
   'const sickLeft = d.sick && !d.cured;', 'const sickLeft = d.sick;', 'caught'],
  ['ワイルドにもお迎えが来るようにする',
   '!pet.departFlag && !isWild() &&', '!pet.departFlag &&', 'caught'],
  ['潜伏中でもくすりを嫌がる',
   "else if(pet.incubAt){", "else if(false){", 'caught'],
  ['恨みが溜まっていても帰還を止めない',
   "if(wrathful() && pet.stage !== 'final') return;", '', 'caught'],
  ['ワイルドでなくても侵攻する',
   "if(pet.stage !== 'final' || !isWild()) return false;",
   "if(pet.stage !== 'final') return false;", 'caught'],
  ['夜に始めると、来た直後に寝てしまう',
   "    pet.wokeUntil = Date.now() + ARRIVE_AWAKE_MS;   // 就寝時間帯に来てもしばらくは起きている", "", 'caught'],
  ['起きている時間が極端に短い',
   "  const ARRIVE_AWAKE_MS = 30 * 60000;", "  const ARRIVE_AWAKE_MS = 1000;", 'caught'],
  ['起きている時間が長すぎて、いつまでも寝ない',
   "  const ARRIVE_AWAKE_MS = 30 * 60000;", "  const ARRIVE_AWAKE_MS = 12 * 3600000;", 'caught'],
  ['名前をつけても時間の起点がそろわない',
   "    pet.lastTick = Date.now();\n    pet.wokeUntil = Date.now() + ARRIVE_AWAKE_MS;",
   "    pet.wokeUntil = Date.now() + ARRIVE_AWAKE_MS;", 'caught'],
  ['夜型シフトを無くす',
   'const OWL_MAX = 5;', 'const OWL_MAX = 0;', 'caught'],
  ['満腹にしても時計を数え直さない（メーターが満タンにならない）',
   "    if(pet.hunger >= HUNGER_MAX && before < HUNGER_MAX) pet.hungerAcc = 0;", "", 'caught'],
  ['満腹でなくても時計を数え直す（いつまでも減らない）',
   "    if(pet.hunger >= HUNGER_MAX && before < HUNGER_MAX) pet.hungerAcc = 0;",
   "    pet.hungerAcc = 0;", 'caught'],
  ['満腹のままおやつを与えても時計が巻き戻る（永久に空腹にならない）',
   "    if(pet.hunger >= HUNGER_MAX && before < HUNGER_MAX) pet.hungerAcc = 0;",
   "    if(pet.hunger >= HUNGER_MAX) pet.hungerAcc = 0;", 'caught'],
  ['きげんを上げても時計を数え直さない（満タンにならない）',
   "      if(pet.mood >= MOOD_MAX) pet.moodAcc = 0;", "", 'caught'],
  ['汚れていても、きげんの時計を数え直してしまう',
   "      if(pet.mood >= MOOD_MAX) pet.moodAcc = 0;", "      pet.moodAcc = 0;", 'caught'],
  ['汚れていてもきげんが満タンまで上がる',
   "  function moodCap(){ return (dirtCount() > 0 || pet.health === 'SICK') ? MOOD_MAX - 1 : MOOD_MAX; }",
   "  function moodCap(){ return MOOD_MAX; }", 'caught'],
  ['ごはんの回復量を段階で変えない',
   "const FEED_GAIN  = { egg: 3, mid: 3, larva: 2, adult: 1, final: 1 };",
   "const FEED_GAIN  = { egg: 1, mid: 1, larva: 1, adult: 1, final: 1 };", 'caught'],
  ['なかよしの上限（100）を外す',
   'pet.B = Math.min(100, pet.B + add);', 'pet.B = pet.B + add;', 'caught'],
  ['読めなかったセーブを黙って捨てる（控えも退避もしない）',
   "  let pet = loadPet() || defaultPet();",
   "  let pet = (()=>{ try{ const sv = JSON.parse(localStorage.getItem(SAVE_KEY)); if(sv && sv.name) return migratePet(sv); }catch(e){} return null; })() || defaultPet();", 'caught'],
  ['読み込めても控えを残さない',
   "if(p){ try{ localStorage.setItem(SAVE_BAK, main); }catch(e){} return p; }",
   "if(p){ return p; }", 'caught'],
  ['読めなかった原文を退避せずに捨てる',
   "      try{ if(main) localStorage.setItem(SAVE_BAD, main); }catch(_){}", "", 'caught'],
  ['本体が壊れていても控えを見に行かない',
   "    if(!broken) return null;", "    return null;", 'caught'],
  ['まだ子がいないだけでも控えを掘り起こす',
   "    if(!broken) return null;", "", 'caught'],
  ['控えから戻すときに移行を通さない',
   "  function readSave(raw){\n    if(!raw) return null;\n    const sv = JSON.parse(raw);\n    return (sv && sv.name) ? migratePet(sv) : null;\n  }",
   "  function readSave(raw){\n    if(!raw) return null;\n    const sv = JSON.parse(raw);\n    return (sv && sv.name) ? Object.assign(defaultPet(), sv) : null;\n  }", 'caught'],
  ['ALL RESET で控えと退避が残る（あとで前の子が掘り起こされる）',
   "      try{ [SAVE_KEY, SAVE_BAK, SAVE_BAD].forEach(k => localStorage.removeItem(k)); }catch(e){}",
   "      try{ localStorage.removeItem(SAVE_KEY); }catch(e){}", 'caught'],
  ['セーブ移行をせず、既定値まかせに戻す',
   'return (sv && sv.name) ? migratePet(sv) : null;',
   'return (sv && sv.name) ? Object.assign(defaultPet(), sv) : null;', 'caught'],
  ['古いセーブに口調を与えない',
   "if(!p.voice && (p.stage === 'adult' || p.stage === 'final')) p.voice = pickVoice(p);", '', 'caught'],
  ['古いセーブのワイルドの印を復元しない',
   "        p.formWild = /3$/.test(p.form || '') && !wasHiddenRoute(p);",
   '        p.formWild = false;', 'caught'],
  ['古いセーブで、隠しルートで進化した子もワイルド扱いにする',
   "&& !wasHiddenRoute(p);", ';', 'caught'],
  ['与えすぎがプリックリーを上書きできてしまう（順序の入れ替え）',
   "if(pet.C < C_FORM_BAD){ pet.formWild = true; return key + '3'; }     // プリックリー\n    if(bigEater() || pampered()) return key + '1';",
   "if(bigEater() || pampered()) return key + '1';\n    if(pet.C < C_FORM_BAD){ pet.formWild = true; return key + '3'; }", 'caught'],
  ['与えすぎがプランプではなくスリークになる',
   "if(bigEater() || pampered()) return key + '1';",
   "if(bigEater() || pampered()) return key + '2';", 'caught'],
  ['甘やかしの道をふさぐ',
   "if(bigEater() || pampered()) return key + '1';",
   "if(bigEater()) return key + '1';", 'caught'],
  ['甘やかしが大食いを兼ねてしまう（片方だけで通る）',
   "if(bigEater() || pampered()) return key + '1';",
   "if(bigEater() && pampered()) return key + '1';", 'caught'],
  ['甘やかしの条件がおやつだけで通ってしまう',
   "return (s.highBDays||0) >= PAMPER_DAYS && ((s.total||{}).snack||0) >= PAMPER_SNACKS; }",
   "return ((s.total||{}).snack||0) >= PAMPER_SNACKS; }", 'caught'],
  ['甘やかしの条件がなかよしだけで通ってしまう',
   "return (s.highBDays||0) >= PAMPER_DAYS && ((s.total||{}).snack||0) >= PAMPER_SNACKS; }",
   "return (s.highBDays||0) >= PAMPER_DAYS; }", 'caught'],
  ['なかよしの連続日数が切れなくなる',
   "pet.highBDays = (pet.B >= B_PAMPER) ? (pet.highBDays||0) + 1 : 0;",
   "pet.highBDays = (pet.highBDays||0) + 1;", 'caught'],
  ['なかよしを保つ線を下げる',
   "const B_PAMPER = 80, PAMPER_DAYS = 5, PAMPER_SNACKS = 25;",
   "const B_PAMPER = 0, PAMPER_DAYS = 5, PAMPER_SNACKS = 25;", 'caught'],
  ['条件がそろわなくても最終形態にしてしまう',
   "    return '';                                                          // まだ最終形態にならない",
   "    return key + '2';", 'caught'],
  ['成体で止める判断を無視して進化させる',
   "      if(!f) return;                              // どの条件にも当たらないうちは成体のまま待つ",
   "      if(!f) { pet.form = 'i2'; }", 'caught'],
  ['スリークの条件が片方だけで通ってしまう',
   "if(pet.C >= C_FORM_GOOD && allRounder()) return key + '2';",
   "if(pet.C >= C_FORM_GOOD || allRounder()) return key + '2';", 'caught'],
  ['ミニゲームの基準を下げる',
   "const ALLROUND = { sw: 600, ss: 700, ab: 400 };",
   "const ALLROUND = { sw: 1, ss: 1, ab: 1 };", 'caught'],
  ['成体で止まる期限を21日に戻す（週1休みの人が間に合わなくなる）',
   "  const STUCK_DAYS      = 28;", "  const STUCK_DAYS      = 21;", 'caught'],
  ['成体で止まる期限を極端に短くする',
   "  const STUCK_DAYS      = 28;", "  const STUCK_DAYS      = 3;", 'caught'],
  ['成体で止まる期限を実質なくす',
   "  const STUCK_DAYS      = 28;", "  const STUCK_DAYS      = 9999;", 'caught'],
  ['成体で止まった子に迎えが来なくなる',
   "    if(pet.stage==='adult' && pet.lineageAt && !pet.ufoFlag && !pet.invadeFlag &&\n       now - pet.lineageAt >= STUCK_DAYS*86400000){",
   "    if(false){", 'caught'],
  ['成体の期限が最終形態の子にも効いてしまう',
   "if(pet.stage==='adult' && pet.lineageAt && !pet.ufoFlag && !pet.invadeFlag &&",
   "if(pet.lineageAt && !pet.ufoFlag && !pet.invadeFlag &&", 'caught'],
  ['古いセーブの判定に、いまの基準を使ってしまう',
   "      return (b.sw||0) >= 250 && (b.ss||0) >= 100 && (b.ab||0) >= 400; }",
   "      return allRounder(q); }", 'caught'],
  ['入れ子の欠けたキーを埋めない',
   "    p.best  = Object.assign({sw:0, ss:0, ab:0}, sv.best);", '', 'caught'],
  ['にっきが1件も無いうちからメニューに並ぶ',
   "  function diaryUnlocked(){ return diaryLog.length > 0; }",
   "  function diaryUnlocked(){ return diaryWriting() || diaryLog.length > 0; }", 'caught'],
  ['にっきがメニューに並ばなくなる',
   "  function diaryUnlocked(){ return diaryLog.length > 0; }",
   "  function diaryUnlocked(){ return false; }", 'caught'],
  ['PRESS A の字が小さいままになる',
   "        ctxO.font = '8px \"Press Start 2P\"';", "        ctxO.font = '6px \"Press Start 2P\"';", 'caught'],
  ['アイコンから降りると右の列に着いてしまう',
   "          if(dir==='down')  menuSel = (r===0) ? menuSel+3 : topLeft;",
   "          if(dir==='down')  menuSel = (r===0) ? menuSel+3 : 6;", 'caught'],
  ['メニューが1列に戻る（読みものが右へ行かない）',
   "  const MENU_RIGHT = ['memory', 'story', 'manual'];", "  const MENU_RIGHT = [];", 'caught'],
  ['右の列に入れる項目をまちがえる',
   "  const MENU_RIGHT = ['memory', 'story', 'manual'];",
   "  const MENU_RIGHT = ['status', 'settings'];", 'caught'],
  ['おもいでが右の列に入らない（左が4行になる）',
   "  const MENU_RIGHT = ['memory', 'story', 'manual'];",
   "  const MENU_RIGHT = ['story', 'manual'];", 'caught'],
  ['列の振り分けで項目が抜け落ちる',
   "    list.forEach((it, i) => (MENU_RIGHT.includes(it[1]) ? right : left).push(i));",
   "    list.forEach((it, i) => { if(MENU_RIGHT.includes(it[1])) right.push(i); });", 'caught'],
  ['おばけになってもおもいでが開かない（死だけ抜ける）',
   "    if(++ghostT === GHOST_MEM_DELAY) endedShowMemory();", "", 'caught'],
  ['おばけになった瞬間におもいでが開く（おばけを見る間が無い）',
   "  const GHOST_MEM_DELAY = GHOST_STILL + GHOST_RISE_T + GHOST_HOLD;",
   "  const GHOST_MEM_DELAY = 1;", 'caught'],
  ['うずくまる間を置かず、いきなり魂が抜ける',
   "  const GHOST_STILL  = 10;", "  const GHOST_STILL  = 0;", 'caught'],
  ['魂が一瞬で昇りきる',
   "  const GHOST_RISE_T = 30;", "  const GHOST_RISE_T = 1;", 'caught'],
  ['昇りきってすぐ おもいで が開く',
   "  const GHOST_HOLD   = 8;", "  const GHOST_HOLD   = 0;", 'caught'],
  ['魂が昇りすぎてヘッダーに掛かる',
   "  const GHOST_Y_TOP  = 30;", "  const GHOST_Y_TOP  = 4;", 'caught'],
  ['魂がほとんど昇らない',
   "  const GHOST_Y_TOP  = 30;", "  const GHOST_Y_TOP  = 48;", 'caught'],
  ['体が薄れて消えない（うずくまったまま残る）',
   "      stampDust(body, bx, by, DM, 1 - dp, dp * GHOST_DUST_X);",
   "      stampDust(body, bx, by, DM, 1, dp * GHOST_DUST_X);", 'caught'],
  ['体が風で流されない（その場で薄れるだけ）',
   "  const GHOST_DUST_X = 12;", "  const GHOST_DUST_X = 0;", 'caught'],
  ['粒ごとの流れ方が同じで、砂埃にならない',
   "  function dustDrift(rx, ry){ return 0.4 + (dustHash(rx, ry) % 13) * 0.1; }",
   "  function dustDrift(rx, ry){ return 1; }", 'caught'],
  ['粒の飛び方が斜めにそろう（／／の筋が出る）',
   "  function dustDrift(rx, ry){ return 0.4 + (dustHash(rx, ry) % 13) * 0.1; }",
   "  function dustDrift(rx, ry){ return 0.5 + ((rx*7 + ry*13) % 6) * 0.2; }", 'caught'],
  ['粒が上下にばらけない',
   "      const y = Math.min(MAIN_GY - 1, oy + ry + Math.round(drift * 0.15 * dustLift(rx, ry)));",
   "      const y = oy + ry;", 'caught'],
  // ── メーターの見え方 ──
  ['満腹のあいだも目減りを描く（食べた直後から欠けて見える）',
   "    if((pet.hunger||0) >= HUNGER_MAX) return HUNGER_MAX;", "", 'caught'],
  ['きげんも上限で保たない',
   "    if((pet.mood||0) >= moodCap()) return pet.mood||0;", "", 'caught'],
  ['きげんを上限ではなく満点で判定する（汚れているとき保たれない）',
   "    if((pet.mood||0) >= moodCap()) return pet.mood||0;",
   "    if((pet.mood||0) >= MOOD_MAX) return pet.mood||0;", 'caught'],

  ['おもいでの日数を、数が後ろの並びに戻す',
   "      ctxR.fillText(petDay() + ' ' + T('mdays'), (W*S)/2, 44*S);",
   "      ctxR.fillText(T('mdays') + '  ' + petDay(), (W*S)/2, 44*S);", 'caught'],

  ['別れかたの2行目を描かない（お迎え・侵攻が言いさしで切れる）',
   "        e.split('\\n').forEach((line, i) => ctxR.fillText(line, (W*S)/2, (MEM_END_Y + i*MEM_END_LH)*S));",
   "        ctxR.fillText(e.split('\\n')[0], (W*S)/2, MEM_END_Y*S);", 'caught'],
  ['餓死と病死で ちがう言葉に戻す',
   "endStarve:'ちからつきた', endSick:'ちからつきた',",
   "endStarve:'ちからつきた', endSick:'びょうきで たおれた',", 'caught'],
  ['別れかたの2行目がページ数に掛かる',
   "  const MEM_END_Y = 50, MEM_END_LH = 5;", "  const MEM_END_Y = 54, MEM_END_LH = 5;", 'caught'],

  ['育成画面を見ていなくても演出が進む（裏で終わって おもいでだけ開く）',
   "    if(scene !== 'main' || miniFrame || manualFrame) return;", "", 'caught'],
  ['門番を時間の進行より手前に置く（画面しだいで時間が止まる）',
   "    advancePet();   // リアルタイム進行（1分単位で処理）",
   "    if(scene !== 'main') return;\n    advancePet();", 'caught'],

  // ── 演出中の操作 ──
  ['演出中でも MENU が開く', "getElementById('mmenu'),()=>{ if(cutscenePlaying()) return; playClick();",
   "getElementById('mmenu'),()=>{ playClick();", 'caught'],
  ['演出中でも 十字が効く', "      if(cutscenePlaying()) return;\n      playClick(900); dpadAnim(el);",
   "      playClick(900); dpadAnim(el);", 'caught'],
  ['おばけを見たあとも操作できないままにする',
   "        || (pet.dead && !pet.memShown)    // 魂が抜けていくあいだ（見たあとの漂う姿は操作できる）",
   "        || pet.dead", 'caught'],

  ['家出の「・・・」をキャラの真上に戻す（退屈のときと位置が食い違う）',
   "      if(ufoT % (RUN_ON + RUN_OFF) < RUN_ON) stampEmo(ctxM, ICO_DOTS, x0, y, cw, NK);",
   "      if(ufoT % (RUN_ON + RUN_OFF) < RUN_ON) stamp(ctxM, ICO_DOTS, x0 + 2, y - 3, NK);", 'caught'],
  ['育成画面のマークだけ別の置き方にする',
   "    function emo(spr){ stampEmo(ctxM, spr, charX, charY + yOff - airOff, gw, NK); }",
   "    function emo(spr){ stamp(ctxM, spr, charX, charY - 3, NK); }", 'caught'],

  ['おもいでが夜に暗くなる（読みものの画面なのに空の色を使う）',
   "    const BG = OFF, DM = DIM, NK = ON;",
   "    const col = getColors(), BG = col.bg, DM = col.dim, NK = col.on;", 'caught'],

  // ── 家出エンディング ──
  ['家出で「・・・」の回数を変える', "  const RUN_ON = 9, RUN_OFF = 7, RUN_TIMES = 3;",
   "  const RUN_ON = 9, RUN_OFF = 7, RUN_TIMES = 5;", 'caught'],
  ['画面の外へ出きる前に終わる（歩いている途中でおもいでが開く）',
   "  function runawayLen(cw){ return RUN_STILL + Math.ceil((centerX(cw) + cw) / RUN_SPEED) + RUN_AFTER; }",
   "  function runawayLen(cw){ return RUN_STILL + Math.ceil(centerX(cw) / RUN_SPEED / 2) + RUN_AFTER; }", 'caught'],
  ['出ていったあとの間を無くす', "  const RUN_AFTER = 14;", "  const RUN_AFTER = 0;", 'caught'],

  // ── おもいでの姿 ──
  ['おもいでの1ページ目に姿を出さない',
   "      if(body) stamp(ctxR, body, Math.round((W - body[0].length)/2), MEM_CHAR_BOT - body.length, NK);",
   "", 'caught'],
  ['姿を上ぞろえで置く（背の高さで下の名前との間隔が変わる）',
   "      if(body) stamp(ctxR, body, Math.round((W - body[0].length)/2), MEM_CHAR_BOT - body.length, NK);",
   "      if(body) stamp(ctxR, body, Math.round((W - body[0].length)/2), 16, NK);", 'caught'],
  ['姿の足元を下げすぎて名前に掛ける',
   "  const MEM_CHAR_BOT = 28;", "  const MEM_CHAR_BOT = 33;", 'caught'],

  // ── 文字の読みやすさ ──
  ['おもいでの見出しを薄い色に戻す（読めない）',
   "      ctxR.font = uiFont(6); ctxR.fillStyle = NK; ctxR.textAlign = 'center';\n      ctxR.fillText(T('mgave'), (W*S)/2, 17*S);",
   "      ctxR.font = uiFont(6); ctxR.fillStyle = DM; ctxR.textAlign = 'center';\n      ctxR.fillText(T('mgave'), (W*S)/2, 17*S);", 'caught'],
  ['日記のページ数を薄い色に戻す',
   "      ctxT.font = uiFont(6); ctxT.fillStyle = ON;\n      ctxT.fillText((diaryPage + 1)",
   "      ctxT.font = uiFont(6); ctxT.fillStyle = DIM;\n      ctxT.fillText((diaryPage + 1)", 'caught'],
  ['「????」の点滅の片側を薄い色に戻す（半分の時間読めない）',
   "    ctxM.fillStyle=(fM%10<5) ? NK : BG;   // 薄色だと読めないので、濃↔消で点滅させる",
   "    ctxM.fillStyle=(fM%10<5) ? NK : DM;", 'caught'],

  ['PRESS A の点滅の片側を薄い色に戻す（半分の時間読めない）',
   "        ctxO.fillStyle = blink ? ON : OFF;   // 薄色だと点滅の半分が読めない",
   "        ctxO.fillStyle = blink ? ON : DIM;", 'caught'],
  ['押せないお世話の名前を薄くする（どの項目にいるか読めない）',
   "        ctxN.fillStyle = ON;\n        ctxN.fillText(T(CARE_ORDER[menuSel].toLowerCase()), (W*S)/2, 36*S);",
   "        ctxN.fillStyle = careDisabled(CARE_ORDER[menuSel]) ? DIM : ON;\n        ctxN.fillText(T(CARE_ORDER[menuSel].toLowerCase()), (W*S)/2, 36*S);", 'caught'],

  // ── ベストスコアの表示 ──
  ['選択画面に点数を出さない',
   "      ctxN.fillText('BEST ' + bestText(playSel), (W*S)/2, 60*S);", "", 'caught'],
  ['選択画面が いつも1つ目のゲームの点数を出す（カーソルに追随しない）',
   "      ctxN.fillText('BEST ' + bestText(playSel), (W*S)/2, 60*S);",
   "      ctxN.fillText('BEST ' + bestText(0), (W*S)/2, 60*S);", 'caught'],
  ['未プレイでも 0点 と出す（遊んで0点だったのと区別がつかない）',
   "    if(!(Number.isFinite(p[k]) && p[k] > 0)) return '---';", "", 'caught'],
  ['おもいでに点数を並べない',
   "      PLAY_ITEMS.forEach((label,i)=> memBestRow(label, bestText(i), 27 + i*8));", "", 'caught'],
  ['おもいでのページ数を増やし忘れる（さいごの すがたへ行けなくなる）',
   "  const MEM_PAGES = 4;", "  const MEM_PAGES = 3;", 'caught'],

  // ── ボタンの字の位置 ──
  ['A・B の字がボタンの中心からずれる（位置合わせを外す）',
   "    transform: translate(0.061em, 0.0625em);", "", 'caught'],
  ['MENU の字がずれる（字間ぶんの補正まで戻す）',
   "    transform: translate(0.103em, 0.0625em);   /* 横は 字間が最後の字のうしろにも入るぶんを含む */",
   "    transform: translate(0.061em, 0.0625em);", 'caught'],

  // ── ミニゲームの逃げ道 ──
  ['ミニゲームが立ち上がらなくても閉じない（画面を覆ったまま固まる）',
   "    miniGuard = setTimeout(()=>{ if(miniFrame === f && !miniAlive(f)) closeMiniGame(true); }, MINI_GUARD_MS);",
   "", 'caught'],
  ['閉じるときに見張りを解除しない（次に開いたゲームを巻き添えにする）',
   "    if(miniGuard){ clearTimeout(miniGuard); miniGuard = 0; }", "", 'caught'],
  ['生死を canvas の有無だけで見る（中が落ちた場合を取り逃す）',
   "      const px = cv.getContext('2d').getImageData(0, 0, 2, 2).data;", "      return true;", 'caught'],

  // ── 端末の時計 ──
  ['時計を戻されても立て直さない（実時間が追いつくまで進行が止まる）',
   "    if(elapsed < 0){ rewindClock(-elapsed); return; }   // 時計が戻された", "", 'caught'],
  ['時計を戻したとき、lastTick だけ直して他の時刻を置き去りにする',
   "    PET_TIMES.forEach(k => { if(pet[k]) pet[k] = Math.max(0, pet[k] - back); });",
   "    pet.lastTick = Date.now();", 'caught'],
  ['DAY の下限を外す（たんじょうが未来だと DAY:-2 と出る）',
   "    return Math.max(1, Math.min(99, days + 1));   // 誕生日=DAY01、次の0:00でDAY02",
   "    return Math.min(99, days + 1);", 'caught'],

  // ── 説明書 ──
  ['タイプの呼び名を変える（説明書だけ古いまま残る）',
   "      gray:'グレイ', martian:'マーシャン', invader:'インベーダー',",
   "      gray:'グレイ', martian:'カセイジン', invader:'インベーダー',", 'caught'],
  ['さいごの分岐を2つに減らす（説明書の「9とおり」と食い違う）',
   "    return n === '1' ? T('plump') : n === '2' ? T('sleek') : n === '3' ? T('prickly') : '';",
   "    return n === '1' ? T('plump') : n === '2' ? T('sleek') : n === '3' ? T('sleek') : '';", 'caught'],

  // ── ストーリー ──
  ['英語だけ段落を足す（日本語と切れ目がずれる）',
   "    'By this little invader.',", "    '',\n    'By this little invader.',", 'caught'],
  ['日本語に漢字が混ざる（この機械は漢字を出さない）',
   "    'この、ちいさな インベーダーに。',", "    'この、小さな インベーダーに。',", 'caught'],
  ['書き出しから雨が消える（到着の演出と辻褄が合わなくなる）',
   "    'その ひは、あさから あめだった。',", "    'その ひは、あさから かぜが つよかった。',", 'caught'],

  // ── 到着の演出 ──
  ['雨が降らない（うすぐらいだけの画面から始まる）',
   "  const ARR_RAIN_N = 14;", "  const ARR_RAIN_N = 0;", 'caught'],
  ['雨がやまない（赤ちゃんが降りてくる裏で降り続ける）',
   "    if(ph > ARR_RAIN_PH) return 0;", "    if(ph > ARR_RAIN_PH) return ARR_RAIN_N;", 'caught'],
  ['ビームより先に雨がやむ（稲光と結びつかない）',
   "  const ARR_RAIN_PH = 2;", "  const ARR_RAIN_PH = 1;", 'caught'],
  ['雨が1コマで消える（止んだというより描き落としに見える）',
   "  const ARR_RAIN_STOP = 4;", "  const ARR_RAIN_STOP = 1;", 'caught'],
  ['雨を見せる間が無い（始まってすぐビームが来る）',
   "  const ARR_PH = [18, 16, 10, 26, 10, 18, 6];",
   "  const ARR_PH = [2, 16, 10, 26, 10, 18, 6];", 'caught'],
  ['ビームが最初から地面まで届いている（伸びてこない）',
   "    if(y > Math.round(ARR_BEAM_TOP + (botY-ARR_BEAM_TOP)*progress)) return -1;", "", 'caught'],
  ['ビームが上に向かってすぼまらず、逆さの円錐になる',
   "    return Math.round(((y-ARR_APEX)/(botY-ARR_APEX)) * ARR_MAX_HALF);",
   "    return Math.round(((botY-y)/(botY-ARR_APEX)) * ARR_MAX_HALF);", 'caught'],
  ['雨をビームより先に描く（光の中の粒が上書きされて消える）',
   "      drawArrivalBeam(beamP, BG);\n      updateArrivalRain(BG, DM, beamP, shown);",
   "      updateArrivalRain(BG, DM, beamP, shown);\n      drawArrivalBeam(beamP, BG);", 'caught'],
  ['雨の粒を暗い色で描く（暗転した画面に沈んで見えない）',
   "        dot(ctxM, d.x, y, (half >= 0 && Math.abs(d.x-ARR_CX) <= half) ? DM : BG);",
   "        dot(ctxM, d.x, y, DM);", 'caught'],
  ['到着の演出が長すぎる（名前をつけるまで待たされる）',
   "  const ARR_PH = [18, 16, 10, 26, 10, 18, 6];",
   "  const ARR_PH = [80, 16, 10, 26, 10, 18, 6];", 'caught'],
  ['雨の粒が画面の外から降ってくる',
   "      y: ARR_BEAM_TOP + Math.random()*(MAIN_GY-1-ARR_BEAM_TOP),",
   "      y: ARR_BEAM_TOP - Math.random()*20,", 'caught'],

  ['昇りはじめと同時に体が散る（魂がまだ中にいるのに崩れる）',
   "      const dp = (p <= s0) ? 0 : (p - s0) / (1 - s0);", "      const dp = p;", 'caught'],
  ['散りはじめが早すぎる（離れる前から崩れる）',
   "    return Math.max(0, Math.min(0.85, (MAIN_GY - bodyTop) / span));",
   "    return 0.05;", 'caught'],
  ['散りはじめが遅すぎて、散る間が無い',
   "    return Math.max(0, Math.min(0.85, (MAIN_GY - bodyTop) / span));",
   "    return 0.99;", 'caught'],
  ['チリが地面より下へ飛ぶ',
   "      const y = Math.min(MAIN_GY - 1, oy + ry + Math.round(drift * 0.15 * dustLift(rx, ry)));",
   "      const y = oy + ry + Math.round(drift * 0.15 * dustLift(rx, ry));", 'caught'],
  ['魂が左右に揺れない',
   "  const GHOST_SWAY_X = 2;", "  const GHOST_SWAY_X = 0;", 'caught'],
  ['魂が揺れすぎる',
   "  const GHOST_SWAY_X = 2;", "  const GHOST_SWAY_X = 14;", 'caught'],
  ['魂の足元が地面より下から出る',
   "        const from  = MAIN_GY - GHOST_SPR.length;",
   "        const from  = by;", 'caught'],
  ['体を薄れさせる仕組みが効かない（最後まで全部残る）',
   "  function fadeKeeps(rx, ry, keep){ return DITHER4[ry & 3][rx & 3] / 16 < keep; }",
   "  function fadeKeeps(rx, ry, keep){ return true; }", 'caught'],
  ['おもいでを見たあとも昇り続ける（画面から消えたままになる）',
   "    if(pet.memShown){", "    if(false){", 'caught'],
  ['おもいでを何度でも開いてしまう',
   "  function endedShowMemory(){ if(!pet.memShown){ pet.memShown = true; savePet(); memOpen('main'); } }",
   "  function endedShowMemory(){ pet.memShown = true; savePet(); memOpen('main'); }", 'caught'],
  ['おもいでがメニューに並ばなくなる',
   "const head = (pet.gone || pet.dead) ? [['MEMORY','memory']] : [];", 'const head = [];', 'caught'],
  ['おもいでが育成中にも並んでしまう',
   "const head = (pet.gone || pet.dead) ? [['MEMORY','memory']] : [];", "const head = [['MEMORY','memory']];", 'caught'],
  ['通算カウンタを数えない',
   "        pet.total.feed++;                                           // 通算（おもいで用）", '', 'caught'],
  ['うまれたては日記を書かないように戻す',
   "function diaryWriting(){ return !!pet.name && !!pet.stage; }",
   "function diaryWriting(){ return !!pet.name && pet.stage !== 'egg'; }", 'caught'],
  ['名前をつける前から日記を書いてしまう',
   "function diaryWriting(){ return !!pet.name && !!pet.stage; }",
   "function diaryWriting(){ return !!pet.stage; }", 'caught'],
  ['日記に段階を焼き付けない（読み返すと今の字になる）',
   "lv: diaryLevel(), wr: Math.round(writeRatio() * 100) / 100 };",
   "wr: Math.round(writeRatio() * 100) / 100 };", 'caught'],
  ['古い日記を、いちばん幼い字として扱ってしまう',
   "return (e && e.lv != null) ? (e.lv|0) : LV_ADULT;",
   "return (e && e.lv != null) ? (e.lv|0) : LV_NEW;", 'caught'],
  ['あかちゃんでも日本語を書けてしまう',
   "const ratio = (lv <= LV_BABY) ? 0 : (e.wr == null ? 1 : e.wr);",
   "const ratio = (e.wr == null ? 1 : e.wr);", 'caught'],
  ['書ける単語の割合を無視して、ぜんぶ書けてしまう',
   "              .map(w => (rnd() < ratio) ? { t: w } : { r: w });",
   "              .map(w => ({ t: w }));", 'caught'],
  ['自分の文字の長さが、もとの単語と合わなくなる',
   "              .map(w => (rnd() < ratio) ? { t: w } : { r: w });",
   "              .map(w => (rnd() < ratio) ? { t: w } : { r: 'あああ' });", 'caught'],
  ['宇宙文字が規則ではなく、字コードまかせになる',
   "    if(k && DIARY_RUNE[k]) return DIARY_RUNE[k];",
   "", 'caught'],
  ['清音と濁音を同じ字にしてしまう',
   "が:'g',ぎ:'g',ぐ:'g',げ:'g',ご:'g',", "が:'k',ぎ:'k',ぐ:'k',げ:'k',ご:'k',", 'caught'],
  ['来たばかりの子の書く量を絞らない',
   "    const cap = Math.min(4, Math.max(1, petDay()));", "    const cap = 4;", 'caught'],
  ['書く量が日を追って増えない（ずっと1話題）',
   "    const cap = Math.min(4, Math.max(1, petDay()));", "    const cap = 1;", 'caught'],
  ['あかちゃんの日記から絵が消える',
   "    if(entryLevel(e) === LV_BABY){", "    if(false){", 'caught'],
  ['こどもの日記にも絵が残ってしまう',
   "    if(entryLevel(e) === LV_BABY){", "    if(entryLevel(e) <= LV_CHILD){", 'caught'],
  ['幼いうちにも結びの言葉を書かせる',
   "      close:  diaryLevel() <= LV_BABY ? '' : voice(),",
   "      close:  voice(),", 'caught'],
  ['日記を開くたびに字の並びが変わる',
   "    const rnd = diaryRnd('w' + (e.cd || '') + (e.d || 0));",
   "    const rnd = () => Math.random();", 'caught'],
  ['うまれたてのページが空になる',
   "    if(!items.length) items.push(pick(DIARY_SCRAWL));",
   "    if(!items.length) return [];", 'caught'],
  ['出来事が絵にならない（絵記号を引かない）',
   "    (e.t || []).forEach(t => { const k = TAG_PICT[t]; if(k) items.push(DIARY_PICT[k]); });",
   "", 'caught'],
  ['英語でも宇宙文字を日本語と同じ大きさで描く（記号だけ大きく浮く）',
   "    return (lv === LV_CHILD) ? Math.min(LV_DOT[lv], textU) : LV_DOT[lv];",
   "    return LV_DOT[lv];", 'caught'],
  ['言葉が混ざらない段階まで文字に合わせて小さくしてしまう',
   "    return (lv === LV_CHILD) ? Math.min(LV_DOT[lv], textU) : LV_DOT[lv];",
   "    return Math.min(LV_DOT[lv], textU);", 'caught'],
  ['本文の文字の大きさを言語で変えない',
   "  function diaryFontSize(){ return (lang === 'ja') ? 10 : 6; }",
   "  function diaryFontSize(){ return 10; }", 'caught'],
  ['段階で字の大きさが変わらない',
   "const LV_DOT = [4, 3, 2, 0];", "const LV_DOT = [2, 2, 2, 0];", 'caught'],
  ['初回起動の言語を英語に戻す',
   "let lang = 'ja';\n  try{ if(localStorage.getItem('myvader_lang') === 'en') lang = 'en'; }catch(e){}",
   "let lang = 'en';\n  try{ if(localStorage.getItem('myvader_lang') === 'ja') lang = 'ja'; }catch(e){}", 'caught'],
  ['体型の呼び名が末尾と対応しなくなる',
   "return n === '1' ? T('plump') : n === '2' ? T('sleek') : n === '3' ? T('prickly') : '';",
   "return n === '1' ? T('sleek') : n === '2' ? T('plump') : n === '3' ? T('prickly') : '';", 'caught'],
  ['別れの形を見分けなくなる',
   "if(pet.goneBy === 'invade') return T('endInvade');", '', 'caught'],
  // 各分岐が個別に就寝判定を持つので、冒頭のガードだけ外しても挙動は変わらない
  ['doCare 冒頭の無効ガードだけ外す',
   '    if(careDisabled(act)) return;\n', '    \n', 'equivalent'],
  ['ページ割りを均さず、上限まで詰めこむ（最後のページだけ すかすかになる）',
   "const pages = layout(lo).length <= n ? layout(lo) : layout(avail);",
   "const pages = layout(avail);", 'caught'],
  ['段落のあいだの空きを詰める（かなの本文が壁のように見える）',
   "const STORY_PARA = 8;", "const STORY_PARA = 0;", 'caught'],
  ['日記の結びを、また「ぶじにおわった」に戻す',
   "{ ja:['ゆうひが しずむのを','ずっと みていた'],  en:['I WATCHED THE SUN','GO DOWN'] },",
   "{ ja:['きょうも ぶじに','おわった'],  en:['ANOTHER DAY','ENDED SAFELY'] },", 'live'],
  ['iOSの割り込み(interrupted)を見のがす（電話のあと ずっと無音になる）',
   "    if(ac.state === 'suspended'){ ac.resume().catch(()=>{}); return; }\n    // interrupted / closed。resume() をひととおり試しつつ、作り直す\n    if(Date.now() - acBornAt < AC_RETRY) return;",
   "    if(ac.state === 'suspended'){ ac.resume().catch(()=>{}); return; }\n    return;\n    if(Date.now() - acBornAt < AC_RETRY) return;", 'caught'],
  ['作り直しても古い口を閉じない（iOSは同時に持てる数に限りがある）',
   "    try{ old.close(); }catch(e){}", "", 'caught'],
  ['割り込み中に口を作り続ける（歯止めを外す）',
   "    if(Date.now() - acBornAt < AC_RETRY) return;", "", 'caught'],
  ['SOUND=OFF でも口を開けてしまう',
   "    if(!soundOn) return;   // SOUND=OFFならミュート\n    ensureAudio();",
   "    ensureAudio();\n    if(!soundOn) return;", 'caught'],
  //  版の番号はコミットのたびに上がるので、番号そのものは書かない。
  //  頭に1字足して sw.js とずらす
  ['画面に出す版を、sw.js とずらす',
   "const APP_VERSION = '", "const APP_VERSION = 'x", 'caught'],
  ['著作権を © で書く（Press Start 2P に無く、1文字だけ字体が浮く）',
   "const APP_COPY = '(C) 2026 Studio M.D.Q.';", "const APP_COPY = '\u00a9 2026 Studio M.D.Q.';", 'caught'],
  ['著作権の名義を落とす',
   "const APP_COPY = '(C) 2026 Studio M.D.Q.';", "const APP_COPY = '(C) 2026';", 'caught'],
  ['SETTINGS の行間をもとの8ドットに戻す（いちばん下が画面から出る）',
   "      const ITEM_H = 7;", "      const ITEM_H = 8;", 'caught'],
  ['バージョンの項目を消す',
   "const SETTINGS_KEYS = ['language','weather','sound','bodycolor','version','reset'];",
   "const SETTINGS_KEYS = ['language','weather','sound','bodycolor','reset'];", 'caught'],
  ['一覧の行にも版の番号を出す（点線と数字でその一行だけ賑やかになる）',
   "                  : key==='debug'     ? (debugMode?T('on'):T('off'))",
   "                  : key==='debug'     ? (debugMode?T('on'):T('off'))\n                  : key==='version'   ? APP_VERSION", 'caught'],
  ['バージョンの画面から版を落とす',
   "        ctxN.fillText('VER ' + APP_VERSION,(W*S)/2, 37*S);", "", 'caught'],
  ['あかちゃんの日記も、読み手の言語で書く（英語だけ字がぎっしり並んで潰れる）',
   "    const src = (lv <= LV_BABY) ? 'ja' : lang;", "    const src = lang;", 'caught'],
  ['こどもの日記まで もとの文面で書く（英語で遊んでいるのに かなが出る）',
   "    const src = (lv <= LV_BABY) ? 'ja' : lang;", "    const src = 'ja';", 'caught'],
  ['列の仕切りを消す',
   "      ctxN.fillRect(26*S + S/4, Y0*S, S/2, rows*HL_H*S);", "", 'caught'],
  ['列の仕切りを、右の列の網掛けに重ねる',
   "      ctxN.fillRect(26*S + S/4, Y0*S, S/2, rows*HL_H*S);",
   "      ctxN.fillRect(27*S + S/4, Y0*S, S/2, rows*HL_H*S);", 'caught'],
  ['列の仕切りを1ドットの太さに戻す（項目の字と同じ太さで、区切りに見えない）',
   "      ctxN.fillRect(26*S + S/4, Y0*S, S/2, rows*HL_H*S);",
   "      ctxN.fillRect(26*S, Y0*S, S, rows*HL_H*S);", 'caught'],
  ['列の仕切りを、ドットの中央からずらす',
   "      ctxN.fillRect(26*S + S/4, Y0*S, S/2, rows*HL_H*S);",
   "      ctxN.fillRect(26*S + S/2, Y0*S, S/2, rows*HL_H*S);", 'caught'],
  ['4行のときも行間を7に戻す（仕切りの下端が画面から出る）',
   "      const HL_H = (rows >= 4) ? 6 : 7;", "      const HL_H = 7;", 'caught'],
  ['くすりの中身の色を輪郭と同じにする（ただの塊に見える）',
   ".......#+++#.\n......#+++++#\n.....#++++++#\n....##++++++#\n...#.##++++#.\n..#...##++#..",
   ".......#####.\n......#######\n.....########\n....#########\n...#.#######.\n..#...#####..", 'caught'],
  ['くすりの輪郭に穴をあける（空いている側が外へつながる）',
   ".#......#....", ".#...........", 'caught'],
  ['くすりを片側だけの塗りつぶしにする（空いている側が無くなる）',
   ".#.....###...\n.#......#....\n.#.....#.....\n..#...#......\n...###.......",
   ".#####+##...\n.#+++++#.....\n.#+++++#.....\n..#+++#......\n...###.......", 'caught'],
  ['押せないアイコンでも、ふだんの音と断りの音が二重に鳴る',
   "    playClick(onDisabledCare() ? 300 : 900);",
   "    playClick(900); setTimeout(()=>playClick(300), 60);", 'caught'],
  ['押せないアイコンでも、ふだんの音だけ鳴る（断られたと分からない）',
   "    playClick(onDisabledCare() ? 300 : 900);", "    playClick(900);", 'caught'],
  ['押せるアイコンまで断りの音になる',
   "    playClick(onDisabledCare() ? 300 : 900);", "    playClick(300);", 'caught'],
  ['サブ画面でもアイコンの状態を見てしまう',
   "    return !inSettings && !inStatus && !inFeed && !inPlay\n        && menuSel < 6 && careDisabled(CARE_ORDER[menuSel]);",
   "    return menuSel < 6 && careDisabled(CARE_ORDER[menuSel]);", 'caught'],
  ['日記のマークが、また未読のときだけ出るようになる',
   "    if(diaryUnlocked()) list.push('diary');", "    if(diaryUnread > 0) list.push('diary');", 'caught'],
  ['ステータスのマークが出ない',
   "    if(!pet.gone && !pet.dead) list.push('status');", "", 'caught'],
  ['別れたあともステータスのマークが残る',
   "    if(!pet.gone && !pet.dead) list.push('status');", "    list.push('status');", 'caught'],
  ['ステータスの知らせが 点きっぱなしになる',
   "  function statusAlert(){ return healthState() !== 'good'; }",
   "  function statusAlert(){ return true; }", 'caught'],
  ['ステータスの知らせが まったく点かない',
   "  function statusAlert(){ return healthState() !== 'good'; }",
   "  function statusAlert(){ return false; }", 'caught'],
  ['知らせを けんこうの文字と別に決める（ふつうでも点く）',
   "  function statusAlert(){ return healthState() !== 'good'; }",
   "  function statusAlert(){ return healthState() !== 'dead'; }", 'caught'],
  ['マークが DAY の表示に重なる',
   "    const right = 130;", "    const right = 152;", 'caught'],
  ['マークが 名前に重なるほど左へ寄る',
   "    const right = 130;", "    const right = 96;", 'caught'],
  ['マークどうしが重なる',
   "  const HEAD_ICON_W = 12, HEAD_ICON_H = 12, HEAD_ICON_GAP = 4;",
   "  const HEAD_ICON_W = 12, HEAD_ICON_H = 12, HEAD_ICON_GAP = -4;", 'caught'],
  ['文字とマークの中心がずれる',
   "  const HEAD_IY = 10;", "  const HEAD_IY = 4;", 'caught'],
  ['マークが ヘッダーの帯からはみ出す',
   "  const HEAD_ICON_W = 12, HEAD_ICON_H = 12, HEAD_ICON_GAP = 4;",
   "  const HEAD_ICON_W = 12, HEAD_ICON_H = 24, HEAD_ICON_GAP = 4;", 'caught'],
  ['3つのマークの大きさがそろわなくなる',
   "    [0,0,0,0,0,1,1,0,0,0,0,0],\n    [0,0,0,0,0,1,1,0,0,0,0,0],\n    [0,0,1,1,1,1,1,1,1,1,0,0],",
   "    [0,0,0,0,0,1,1,0,0,0,0],\n    [0,0,0,0,0,1,1,0,0,0,0],\n    [0,0,1,1,1,1,1,1,1,1],", 'caught'],
  ['ヘッダーのマークの左右が入れかわる',
   "    if(diaryUnlocked()) list.push('diary');                 // 1件も書かれていないうちは、選ばせない（開いても空）\n    if(!pet.gone && !pet.dead) list.push('status');",
   "    if(!pet.gone && !pet.dead) list.push('status');\n    if(diaryUnlocked()) list.push('diary');                 // 1件も書かれていないうちは、選ばせない（開いても空）", 'caught'],
  ['日記が1件も無くても、日記のマークが選べてしまう',
   "    if(diaryUnlocked()) list.push('diary');", "    list.push('diary');", 'caught'],
  ['えらんでいるマークを薄色のまま描く（薄色の枠に溶けて消える）',
   "(sel || blink) ? NK : DM", "blink ? NK : DM", 'caught'],
  ['ステータスの棒が ぜんぶ同じ長さになる（グラフに見えない）',
   "    [1,1,1,1,1,1,1,1,0,0,0,0],\n    [1,1,1,1,1,1,1,1,0,0,0,0],\n    [1,1,1,1,1,1,1,1,0,0,0,0],",
   "    [1,1,1,1,1,0,0,0,0,0,0,0],\n    [1,1,1,1,1,0,0,0,0,0,0,0],\n    [1,1,1,1,1,0,0,0,0,0,0,0],", 'caught'],
  ['ステータスの棒が「長い・短い・長い」に戻る（E の字に見える）',
   "    [1,1,1,1,1,0,0,0,0,0,0,0],\n    [1,1,1,1,1,0,0,0,0,0,0,0],\n    [1,1,1,1,1,0,0,0,0,0,0,0],",
   "    [1,1,1,1,1,1,1,1,1,1,1,1],\n    [1,1,1,1,1,1,1,1,1,1,1,1],\n    [1,1,1,1,1,1,1,1,1,1,1,1],", 'caught'],
  ['ステータスの棒から左の軸が消える',
   "    [1,0,0,0,0,0,0,0,0,0,0,0],\n    [1,1,1,1,1,0,0,0,0,0,0,0],", "    [0,0,0,0,0,0,0,0,0,0,0,0],\n    [0,1,1,1,1,0,0,0,0,0,0,0],", 'caught'],
  ['ステータスの棒のあいだの空きが無くなる（ひとかたまりに見える）',
   "    [1,0,0,0,0,0,0,0,0,0,0,0],\n    [1,1,1,1,1,1,1,1,0,0,0,0],", "    [1,1,1,1,1,1,0,0,0,0,0,0],\n    [1,1,1,1,1,1,1,1,0,0,0,0],", 'caught'],
  ['日記の中の横線が減る（ただの箱に見える）',
   "    [1,1,0,1,1,1,1,1,1,1,0,1],\n    [1,1,0,0,0,0,0,0,0,0,0,1],\n    [1,1,0,0,0,0,0,0,0,0,0,1],\n    [1,1,0,1,1,1,1,1,1,1,0,1],",
   "    [1,1,0,0,0,0,0,0,0,0,0,1],\n    [1,1,0,0,0,0,0,0,0,0,0,1],\n    [1,1,0,0,0,0,0,0,0,0,0,1],\n    [1,1,0,0,0,0,0,0,0,0,0,1],", 'caught'],
  ['せっていのマークが出ない',
   "    list.push('settings');                                  // せっていは いつでも開ける", "", 'caught'],
  ['せっていのマークが 知らせを持ってしまう（点滅する）',
   "    return k === 'status' ? statusAlert()\n         : k === 'diary'  ? diaryUnread > 0\n         : false;",
   "    return k === 'status' ? statusAlert()\n         : k === 'diary'  ? diaryUnread > 0\n         : true;", 'caught'],
  ['せっていのマークだけ いつも濃い色になる（ほかと ちぐはぐに見える）',
   "(sel || blink) ? NK : DM", "(sel || blink || k === 'settings') ? NK : DM", 'caught'],
  ['上を押すと、点滅を無視していちばん左が選ばれる',
   "        if(el.classList.contains('up')   && !headSel) headSel = headDefault();",
   "        if(el.classList.contains('up')   && !headSel) headSel = list[0];", 'caught'],
  ['両方点滅しているとき、日記が先に選ばれる',
   "    for(const k of ['status', 'diary']) if(list.includes(k) && headAlert(k)) return k;",
   "    for(const k of ['diary', 'status']) if(list.includes(k) && headAlert(k)) return k;", 'caught'],
  ['どれも点いていないとき、せっていではなく いちばん左が選ばれる',
   "    return list.includes('settings') ? 'settings' : list[0];", "    return list[0];", 'caught'],
  ['命名前でも ヘッダーのマークが出る（???? が選べなくなる）',
   "    if(!pet.name) return list;                              // 命名前は ????（名前）を選ばせる", "", 'caught'],
  ['マークと DAY のあいだの仕切りを消す',
   "      ctxM.fillRect(last + HEAD_ICON_GAP/2, HEAD_IY, S/2, HEAD_ICON_H);", "", 'caught'],
  ['仕切りを マークと同じ太さにする（もう1つマークがあるように見える）',
   "      ctxM.fillRect(last + HEAD_ICON_GAP/2, HEAD_IY, S/2, HEAD_ICON_H);",
   "      ctxM.fillRect(last + HEAD_ICON_GAP/2, HEAD_IY, S, HEAD_ICON_H);", 'caught'],
  ['マークが1つも無くても 仕切りを引く',
   "    if(list.length){\n      const last = headIconX(list.length-1, list.length) + HEAD_ICON_W;",
   "    {\n      const last = headIconX(Math.max(0,list.length-1), Math.max(1,list.length)) + HEAD_ICON_W;", 'caught'],
];

const orig = fs.readFileSync(GAME, 'utf8');
let caught = 0, missed = [], unexpected = [];
try {
  process.stdout.write('突然変異チェック（本体をわざと壊して、テストが落ちるかを見る）\n\n');
  for(const [name, from, to, expect] of MUTATIONS){
    if(orig.split(from).length - 1 !== 1){
      console.log(`  ？ 対象が1か所に定まらない  ${name}`); continue;
    }
    fs.writeFileSync(GAME, orig.replace(from, to));
    let died = false;
    try { execFileSync(process.execPath, [TEST], { stdio: 'pipe' }); }
    catch(e){ died = true; }
    const good = (expect === 'caught') ? died : !died;
    if(good && expect === 'caught') caught++;
    if(!good && expect === 'caught') missed.push(name);
    if(!good && expect === 'equivalent') unexpected.push(name);
    const mark = good ? (expect === 'caught' ? '✓ 検出' : '－ 挙動不変') : '✗ 見逃し';
    console.log(`  ${mark}  ${name}`);
  }
} finally {
  fs.writeFileSync(GAME, orig);
}
console.log('\n本体は元に戻した');
const total = MUTATIONS.filter(m => m[3] === 'caught').length;
console.log(`検出 ${caught} / ${total}`);
if(missed.length) console.log('見逃し: ' + missed.join(' , '));
process.exit(missed.length ? 1 : 0);
